import { randomUUID } from "node:crypto";
import { getDb } from "../persistence/db.js";
import type { Planner, PlanStepSpec, PlanRun } from "../planning/planner.js";
import type { ServiceRegistry } from "../orchestration/serviceRegistry.js";

export type WorkflowStatus="DRAFT"|"ACTIVE"|"DISABLED"|"ARCHIVED";
export type WorkflowSource="BUILTIN"|"LEARNED"|"USER";
export interface Workflow {id:string;name:string;description:string;status:WorkflowStatus;source:WorkflowSource;version:number;inputSchema:Record<string,unknown>;objectiveTemplate:string;steps:PlanStepSpec[];createdFromPlanRunId?:string;createdAt:number;updatedAt:number;lastSuccessAt?:number;successCount:number}
const row=(r:any):Workflow=>({id:r.id,name:r.name,description:r.description,status:r.status,source:r.source,version:r.version,inputSchema:JSON.parse(r.input_schema_json),objectiveTemplate:r.objective_template,steps:JSON.parse(r.steps_json),createdFromPlanRunId:r.created_from_plan_run_id??undefined,createdAt:r.created_at,updatedAt:r.updated_at,lastSuccessAt:r.last_success_at??undefined,successCount:r.success_count});
const secret=/authorization|api[_-]?key|token|secret|password|bearer/i;
function safe(value:unknown):unknown {if(Array.isArray(value))return value.map(safe);if(value&&typeof value==="object")return Object.fromEntries(Object.entries(value as Record<string,unknown>).filter(([k])=>!secret.test(k)).map(([k,v])=>[k,safe(v)]));if(typeof value==="string"&&(/^(?:\/|[A-Za-z]:\\)/.test(value)||secret.test(value)))return "[redacted]";return value;}
function substitute(value:unknown,inputs:Record<string,unknown>,known:Set<string>):unknown {if(Array.isArray(value))return value.map(v=>substitute(v,inputs,known));if(value&&typeof value==="object")return Object.fromEntries(Object.entries(value as Record<string,unknown>).map(([k,v])=>[k,substitute(v,inputs,known)]));if(typeof value!=="string")return value;return value.replace(/{{\s*([A-Za-z_][A-Za-z0-9_]*)\s*}}/g,(_,key)=>{if(!known.has(key))throw new Error(`UNKNOWN_WORKFLOW_VARIABLE: ${key}`);return inputs[key]===undefined?"":String(inputs[key]);});}
export class WorkflowRegistry {
 constructor(){this.ensureBuiltins();}
 private insert(w:Omit<Workflow,"createdAt"|"updatedAt"|"successCount">){const now=Date.now();getDb().prepare(`INSERT OR IGNORE INTO workflows(id,name,description,status,source,version,input_schema_json,objective_template,steps_json,created_from_plan_run_id,created_at,updated_at,success_count)VALUES(?,?,?,?,?,?,?,?,?,?,?,?,0)`).run(w.id,w.name,w.description,w.status,w.source,w.version,JSON.stringify(w.inputSchema),w.objectiveTemplate,JSON.stringify(w.steps),w.createdFromPlanRunId??null,now,now);}
 private ensureBuiltins(){this.insert({id:"compare_sources",name:"compare_sources",description:"Compare des sources par recherche approfondie.",status:"ACTIVE",source:"BUILTIN",version:1,inputSchema:{type:"object",properties:{topic:{type:"string"},queries:{type:"array"}},required:["topic"]},objectiveTemplate:"Comparer les sources sur {{topic}}",steps:[{local_id:"research",title:"Rechercher et comparer les sources",capability:"deep_research",objective:"Comparer les sources sur {{topic}}",context:{queries:"{{queries}}"},constraints:[],priority:"medium",depends_on:[]}]});this.insert({id:"monitor_web",name:"monitor_web",description:"Surveille le Web au moyen du WATCH existant.",status:"ACTIVE",source:"BUILTIN",version:1,inputSchema:{type:"object",properties:{title:{type:"string"},objective:{type:"string"},repeatIntervalMs:{type:"number"},firstRunAt:{type:"number"},queries:{type:"array"}},required:["title","objective","repeatIntervalMs","firstRunAt"]},objectiveTemplate:"{{objective}}",steps:[{local_id:"monitor",title:"{{title}}",capability:"deep_research",objective:"{{objective}}",context:{queries:"{{queries}}",monitor:{repeatIntervalMs:"{{repeatIntervalMs}}",firstRunAt:"{{firstRunAt}}"}},constraints:[],priority:"medium",depends_on:[]}]});}
 list(){return (getDb().prepare("SELECT * FROM workflows ORDER BY name").all() as any[]).map(row);} get(idOrName:string){const r=getDb().prepare("SELECT * FROM workflows WHERE id=? OR name=?").get(idOrName,idOrName);return r?row(r):null;}
 setStatus(id:string,status:WorkflowStatus){if(!["ACTIVE","DISABLED","ARCHIVED"].includes(status))throw new Error("INVALID_WORKFLOW_STATUS");return getDb().prepare("UPDATE workflows SET status=?,updated_at=? WHERE id=?").run(status,Date.now(),id).changes===1;}
 compile(workflow:Workflow,inputs:Record<string,unknown>):{objective:string;steps:PlanStepSpec[]}{const schema=workflow.inputSchema as any,known=new Set(Object.keys(schema.properties??{}));for(const key of Object.keys(inputs))if(!known.has(key))throw new Error(`UNKNOWN_WORKFLOW_VARIABLE: ${key}`);for(const key of schema.required??[])if(inputs[key]===undefined)throw new Error(`MISSING_WORKFLOW_INPUT: ${key}`);return {objective:substitute(workflow.objectiveTemplate,inputs,known) as string,steps:substitute(workflow.steps,inputs,known) as PlanStepSpec[]};}
 execute(idOrName:string,inputs:Record<string,unknown>,planner:Planner,services:ServiceRegistry):PlanRun {const w=this.get(idOrName);if(!w||w.status!=="ACTIVE")throw new Error("WORKFLOW_NOT_ACTIVE");const compiled=this.compile(w,inputs);return planner.createExecutionPlan(compiled.objective,compiled.steps,services);}
 learnFromPlan(planRunId:string,planner:Planner):Workflow {const run=planner.getRun(planRunId);if(!run||run.status!=="COMPLETED"||planner.activeRuns().some(x=>x.id!==planRunId))throw new Error("PLAN_NOT_LEARNABLE");const steps=planner.nodes(planRunId).map((n,i)=>({local_id:`step_${i+1}`,title:n.title.replace(/[0-9a-f]{8}-[0-9a-f-]{27}/gi,"item"),capability:n.capability!,objective:n.objective!,context:safe(n.context) as Record<string,unknown>,constraints:safe(n.constraints) as string[],priority:n.priority!,depends_on:n.dependencies.map(d=>`step_${planner.nodes(planRunId).findIndex(x=>x.id===d)+1}`).filter(x=>x!=="step_0")}));const id=randomUUID();this.insert({id,name:`learned_${id.slice(0,8)}`,description:"Workflow appris depuis une mission réussie.",status:"DRAFT",source:"LEARNED",version:1,inputSchema:{type:"object",properties:{}},objectiveTemplate:"Mission réutilisable",steps,createdFromPlanRunId:planRunId});return this.get(id)!;}
}
