/**
 * Catalogue réel des SkillDescriptor (chantier Skills & Capabilities, plan V5
 * §PHASE 11/12). Issu d'un audit factuel du dépôt (services réels de
 * `config/services.json`, skills réels de `src/skills/runtime.ts` et
 * `src/skills/builtin/*.ts`, Software Factory de `src/services/
 * softwareFactoryService.ts` + `src/repository/*`) — AUCUN service ni skill
 * n'est inventé ici : chaque entrée cite un fichier réel du dépôt comme
 * `toolsRequired`/référence de schéma, et chaque `status="AVAILABLE"` cite
 * au moins un test réel déjà existant comme preuve (`proofRefs`).
 *
 * `status`/`remediationType` reflètent l'état RÉEL constaté à l'audit
 * (ex. les 4 bureaux métier sont `DISABLED` car `enabled:false` dans
 * `config/services.json` ; `read_ci_status`/`read_main_protection` sont
 * `MISSING` car `githubReadOnlyClient.ts` les implémente et les teste, mais
 * aucun skill ne les expose encore à l'agent — un vrai gap, pas une
 * supposition).
 *
 * Ce catalogue ne couvre PAS les skills de contrôle interne (`get_current_time`,
 * `remember_fact`, `execute_code`, `execute_mission`, `execute_workflow`,
 * `manage_skill`, `inspect_task`/`cancel_task`/`schedule_task`/
 * `monitor_condition`) : voir `gapAnalysis.ts` §"actions humaines requises"
 * pour ce backlog explicite plutôt que de les cataloguer par supposition.
 */

import { defineSkill, type SkillDescriptor } from "./skillManifest.js";

/** Horodatage de cet audit — réutilisé par toutes les entrées `lastVerifiedAt` de ce fichier. */
export const SKILL_CATALOG_AUDITED_AT = Date.parse("2026-09-14T00:00:00Z");

export const REAL_SKILL_CATALOG: readonly SkillDescriptor[] = Object.freeze([
  defineSkill({
    skillId: "software_development",
    skillName: "Développement logiciel (Software Factory)",
    skillVersion: "1.0.0",
    description: "Délègue une modification logicielle réelle (branche, commit, PR GitHub) à la Software Factory. Jamais de fusion automatique (neverAutoMerge).",
    serviceScope: { type: "SINGLE_SERVICE", serviceId: "software_factory" },
    capabilitiesProvided: ["software_development"],
    toolsRequired: ["octokit.git.createRef", "octokit.repos.createOrUpdateFileContents", "octokit.pulls.create", "src/repository/secretScanner.ts#scanForSecrets", "src/services/diffFidelity.ts#checkDiffFidelity"],
    dependencies: [],
    inputSchemaRef: "src/skills/runtime.ts#software_development.parameters",
    outputSchemaRef: "src/orchestration/serviceOrchestrator.ts#OrchestrationResult",
    riskLevel: "MEDIUM",
    permissionLevel: "WRITE",
    sideEffects: true,
    idempotent: false,
    asyncSupported: true,
    timeoutMs: 600000,
    testRefs: ["src/services/softwareFactoryService.test.ts", "src/skills/softwareFactoryChain.test.ts", "src/orchestration/softwareFactoryLocal.test.ts"],
    proofRefs: ["TEST:src/services/softwareFactoryService.test.ts", "TEST:src/skills/softwareFactoryChain.test.ts"],
    status: "AVAILABLE",
    lastVerifiedAt: SKILL_CATALOG_AUDITED_AT,
  }),
  defineSkill({
    skillId: "code_generation",
    skillName: "Génération de code (Software Factory)",
    skillVersion: "1.0.0",
    description: "Capacité déclarée par software_factory (config/services.json) mais partageant le même handler que software_development sans test qui l'exerce distinctement — statut honnête NOT_TESTED.",
    serviceScope: { type: "SINGLE_SERVICE", serviceId: "software_factory" },
    capabilitiesProvided: ["code_generation"],
    toolsRequired: ["src/services/softwareFactoryService.ts#SoftwareFactoryService.handleTaskRequest"],
    dependencies: [],
    inputSchemaRef: "src/orchestration/contract.ts#TaskRequest",
    outputSchemaRef: "src/orchestration/serviceOrchestrator.ts#OrchestrationResult",
    riskLevel: "LOW",
    permissionLevel: "READ",
    sideEffects: true,
    idempotent: false,
    asyncSupported: true,
    timeoutMs: 600000,
    testRefs: [],
    proofRefs: [],
    status: "NOT_TESTED",
    remediationType: "ADD_TEST",
    lastVerifiedAt: SKILL_CATALOG_AUDITED_AT,
  }),
  defineSkill({
    skillId: "file_management",
    skillName: "Gestion de fichiers workspace",
    skillVersion: "1.0.0",
    description: "Liste, lit, écrit ou supprime un fichier dans un workspace sandboxé (WorkspaceStore).",
    serviceScope: { type: "SINGLE_SERVICE", serviceId: "workspace_service" },
    capabilitiesProvided: ["file_management"],
    toolsRequired: ["src/workspaces/workspaceStore.ts#WorkspaceStore"],
    dependencies: [],
    inputSchemaRef: "src/skills/runtime.ts#file_management.parameters",
    outputSchemaRef: "src/orchestration/serviceOrchestrator.ts#OrchestrationResult",
    riskLevel: "MEDIUM",
    permissionLevel: "WRITE",
    sideEffects: true,
    idempotent: false,
    asyncSupported: false,
    timeoutMs: 30000,
    testRefs: ["src/workspaces/workspaces.test.ts", "src/orchestration/workspaceHardening.test.ts"],
    proofRefs: ["TEST:src/workspaces/workspaces.test.ts"],
    status: "AVAILABLE",
    lastVerifiedAt: SKILL_CATALOG_AUDITED_AT,
  }),
  defineSkill({
    skillId: "deep_research",
    skillName: "Recherche approfondie",
    skillVersion: "1.0.0",
    description: "Effectue une recherche Web approfondie et documentée via research_service, produit un rapport en artefact de workspace.",
    serviceScope: { type: "SINGLE_SERVICE", serviceId: "research_service" },
    capabilitiesProvided: ["deep_research"],
    toolsRequired: ["src/services/researchService.ts#ResearchService.handleTaskRequest", "src/web/searchFactory.ts#createWebSearchProvider"],
    dependencies: [],
    inputSchemaRef: "src/skills/runtime.ts#deep_research.parameters",
    outputSchemaRef: "src/orchestration/serviceOrchestrator.ts#OrchestrationResult",
    riskLevel: "LOW",
    permissionLevel: "READ",
    sideEffects: true,
    idempotent: false,
    asyncSupported: true,
    timeoutMs: 120000,
    testRefs: ["src/orchestration/agenticPower.test.ts"],
    proofRefs: ["TEST:src/orchestration/agenticPower.test.ts"],
    status: "AVAILABLE",
    lastVerifiedAt: SKILL_CATALOG_AUDITED_AT,
  }),
  defineSkill({
    skillId: "knowledge_search",
    skillName: "Intelligence dépôt (lecture seule)",
    skillVersion: "1.0.0",
    description: "Inspecte un dépôt GitHub en lecture seule : arborescence, fichiers, recherche, PR, commits, diffs. Strictement lecture seule, aucune écriture GitHub.",
    serviceScope: { type: "TRANSVERSAL" },
    capabilitiesProvided: ["knowledge_search"],
    toolsRequired: ["src/repository/githubReadOnlyClient.ts#GithubReadOnlyClient", "src/repository/repositoryIntelligenceEngine.ts"],
    dependencies: [],
    inputSchemaRef: "src/skills/runtime.ts#knowledge_search.parameters",
    outputSchemaRef: "src/repository/repositoryIntelligenceEngine.ts#FileReadResult",
    riskLevel: "LOW",
    permissionLevel: "READ",
    sideEffects: false,
    idempotent: true,
    asyncSupported: false,
    timeoutMs: 30000,
    probeId: "probe.knowledge_search.read_repository",
    testRefs: ["src/repository/repositoryIntelligenceEngine.test.ts", "src/skills/knowledgeSearch.test.ts", "src/repository/githubReadOnlyClient.test.ts"],
    proofRefs: ["TEST:src/repository/repositoryIntelligenceEngine.test.ts"],
    status: "AVAILABLE",
    lastVerifiedAt: SKILL_CATALOG_AUDITED_AT,
  }),
  defineSkill({
    skillId: "web_search",
    skillName: "Recherche Web",
    skillVersion: "1.0.0",
    description: "Recherche des informations actuelles sur le Web via le provider configuré (UNAVAILABLE si config.webSearch.provider=none, non modélisé ici — décision runtime, cf. src/skills/runtime.ts).",
    serviceScope: { type: "TRANSVERSAL" },
    capabilitiesProvided: ["web_search"],
    toolsRequired: ["src/web/searchFactory.ts#createWebSearchProvider"],
    dependencies: [],
    inputSchemaRef: "src/types.ts#SkillDefinition.parameters",
    outputSchemaRef: "src/web/searchProvider.ts",
    riskLevel: "LOW",
    permissionLevel: "READ",
    sideEffects: false,
    idempotent: true,
    asyncSupported: false,
    timeoutMs: 15000,
    probeId: "probe.web_search.controlled_query",
    testRefs: ["src/skills/reusableIntelligence.test.ts", "src/core/agent.test.ts"],
    proofRefs: ["TEST:src/skills/reusableIntelligence.test.ts"],
    status: "AVAILABLE",
    lastVerifiedAt: SKILL_CATALOG_AUDITED_AT,
  }),
  defineSkill({
    skillId: "document_work",
    skillName: "Lecture/recherche de documents",
    skillVersion: "1.0.0",
    description: "Lit et recherche dans des documents (txt, markdown, JSON, CSV, HTML, PDF) d'un workspace, borné, sans OCR.",
    serviceScope: { type: "TRANSVERSAL" },
    capabilitiesProvided: ["document_work"],
    toolsRequired: ["src/workbench/documentEngine.ts#readDocument"],
    dependencies: [],
    inputSchemaRef: "src/skills/runtime.ts#document_work.parameters",
    outputSchemaRef: "src/workbench/documentEngine.ts#DocumentReadResult",
    riskLevel: "LOW",
    permissionLevel: "READ",
    sideEffects: false,
    idempotent: true,
    asyncSupported: false,
    timeoutMs: 15000,
    probeId: "probe.document_work.read_fixture",
    testRefs: ["src/workbench/workbench.test.ts"],
    proofRefs: ["TEST:src/workbench/workbench.test.ts"],
    status: "AVAILABLE",
    lastVerifiedAt: SKILL_CATALOG_AUDITED_AT,
  }),
  defineSkill({
    skillId: "spreadsheet_work",
    skillName: "Tableurs",
    skillVersion: "1.0.0",
    description: "Liste les feuilles, inspecte, lit, filtre, trie, agrège et exporte des tableurs (CSV, TSV, XLSX) d'un workspace.",
    serviceScope: { type: "TRANSVERSAL" },
    capabilitiesProvided: ["spreadsheet_work"],
    toolsRequired: ["src/workbench/spreadsheetEngine.ts"],
    dependencies: [],
    inputSchemaRef: "src/skills/runtime.ts#spreadsheet_work.parameters",
    outputSchemaRef: "src/workbench/spreadsheetEngine.ts",
    riskLevel: "MEDIUM",
    permissionLevel: "WRITE",
    sideEffects: true,
    idempotent: false,
    asyncSupported: false,
    timeoutMs: 30000,
    testRefs: ["src/workbench/workbench.test.ts"],
    proofRefs: ["TEST:src/workbench/workbench.test.ts"],
    status: "AVAILABLE",
    lastVerifiedAt: SKILL_CATALOG_AUDITED_AT,
  }),
  defineSkill({
    skillId: "data_analysis",
    skillName: "Analyse de données",
    skillVersion: "1.0.0",
    description: "Calcule des statistiques (agrégats, corrélation, groupby, séries temporelles, outliers) sur un tableau borné d'un workspace.",
    serviceScope: { type: "TRANSVERSAL" },
    capabilitiesProvided: ["data_analysis"],
    toolsRequired: ["src/workbench/dataAnalysisEngine.ts#runDataAnalysis"],
    dependencies: [],
    inputSchemaRef: "src/skills/runtime.ts#data_analysis.parameters",
    outputSchemaRef: "src/workbench/dataAnalysisEngine.ts",
    riskLevel: "LOW",
    permissionLevel: "READ",
    sideEffects: false,
    idempotent: true,
    asyncSupported: false,
    timeoutMs: 30000,
    testRefs: ["src/workbench/workbench.test.ts"],
    proofRefs: ["TEST:src/workbench/workbench.test.ts"],
    status: "AVAILABLE",
    lastVerifiedAt: SKILL_CATALOG_AUDITED_AT,
  }),
  defineSkill({
    skillId: "database_query",
    skillName: "Requête base de données (lecture seule)",
    skillVersion: "1.0.0",
    description: "Exécute une requête SQL en lecture seule (SELECT/WITH) sur une base SQLite du workspace.",
    serviceScope: { type: "TRANSVERSAL" },
    capabilitiesProvided: ["database_query"],
    toolsRequired: ["src/workbench/databaseEngine.ts#runDatabaseQuery"],
    dependencies: [],
    inputSchemaRef: "src/skills/runtime.ts#database_query.parameters",
    outputSchemaRef: "src/workbench/databaseEngine.ts#DatabaseQueryResult",
    riskLevel: "LOW",
    permissionLevel: "READ",
    sideEffects: false,
    idempotent: true,
    asyncSupported: false,
    timeoutMs: 15000,
    probeId: "probe.database_query.select_1",
    testRefs: ["src/workbench/workbench.test.ts"],
    proofRefs: ["TEST:src/workbench/workbench.test.ts"],
    status: "AVAILABLE",
    lastVerifiedAt: SKILL_CATALOG_AUDITED_AT,
  }),
  defineSkill({
    skillId: "report_generation",
    skillName: "Génération de rapport",
    skillVersion: "1.0.0",
    description: "Génère et persiste un rapport (Markdown ou JSON) terminé dans le workspace via l'ArtifactStore.",
    serviceScope: { type: "TRANSVERSAL" },
    capabilitiesProvided: ["report_generation"],
    toolsRequired: ["src/workbench/reportEngine.ts#generateReport"],
    dependencies: [],
    inputSchemaRef: "src/skills/runtime.ts#report_generation.parameters",
    outputSchemaRef: "src/workbench/reportEngine.ts",
    riskLevel: "MEDIUM",
    permissionLevel: "WRITE",
    sideEffects: true,
    idempotent: false,
    asyncSupported: false,
    timeoutMs: 15000,
    testRefs: ["src/workbench/workbench.test.ts"],
    proofRefs: ["TEST:src/workbench/workbench.test.ts"],
    status: "AVAILABLE",
    lastVerifiedAt: SKILL_CATALOG_AUDITED_AT,
  }),
  defineSkill({
    skillId: "run_agent_team",
    skillName: "Équipe multi-agents",
    skillVersion: "1.0.0",
    description: "Délègue un objectif à une équipe de profils spécialisés coordonnés (MultiAgentCoordinator), avec reprise possible d'un run interrompu.",
    serviceScope: { type: "TRANSVERSAL" },
    capabilitiesProvided: ["run_agent_team"],
    toolsRequired: ["src/agents/multiAgentCoordinator.ts#MultiAgentCoordinator"],
    dependencies: [],
    inputSchemaRef: "src/skills/builtin/agentTeam.ts",
    outputSchemaRef: "src/agents/types.ts",
    riskLevel: "MEDIUM",
    permissionLevel: "WRITE",
    sideEffects: true,
    idempotent: false,
    asyncSupported: true,
    timeoutMs: 300000,
    testRefs: ["src/agents/multiAgentCoordinator.test.ts"],
    proofRefs: ["TEST:src/agents/multiAgentCoordinator.test.ts"],
    status: "AVAILABLE",
    lastVerifiedAt: SKILL_CATALOG_AUDITED_AT,
  }),

  // --- Bureaux métier (Chantier 9) : réels, testés, mais enabled:false dans config/services.json. ---
  defineSkill({
    skillId: "product_studio",
    skillName: "Product Studio",
    skillVersion: "1.0.0",
    description: "Bureau métier produit — désactivé par défaut (config/services.json: enabled=false).",
    serviceScope: { type: "SINGLE_SERVICE", serviceId: "product_studio" },
    capabilitiesProvided: ["product_studio"],
    toolsRequired: ["src/services/productStudioService.ts#ProductStudioService.handleTaskRequest"],
    dependencies: [],
    inputSchemaRef: "src/skills/builtin/productStudio.ts",
    outputSchemaRef: "src/orchestration/serviceOrchestrator.ts#OrchestrationResult",
    riskLevel: "LOW",
    permissionLevel: "READ",
    sideEffects: true,
    idempotent: false,
    asyncSupported: false,
    timeoutMs: 60000,
    testRefs: ["src/services/productStudioService.test.ts"],
    proofRefs: [],
    status: "DISABLED",
    remediationType: "CONNECT_SERVICE",
    lastVerifiedAt: SKILL_CATALOG_AUDITED_AT,
  }),
  defineSkill({
    skillId: "creative_studio",
    skillName: "Creative Studio",
    skillVersion: "1.0.0",
    description: "Bureau métier créatif — désactivé par défaut (config/services.json: enabled=false). Ne génère pas d'images lui-même.",
    serviceScope: { type: "SINGLE_SERVICE", serviceId: "creative_studio" },
    capabilitiesProvided: ["creative_studio"],
    toolsRequired: ["src/services/creativeStudioService.ts#CreativeStudioService.handleTaskRequest"],
    dependencies: [],
    inputSchemaRef: "src/skills/builtin/creativeStudio.ts",
    outputSchemaRef: "src/orchestration/serviceOrchestrator.ts#OrchestrationResult",
    riskLevel: "LOW",
    permissionLevel: "READ",
    sideEffects: true,
    idempotent: false,
    asyncSupported: false,
    timeoutMs: 60000,
    testRefs: ["src/services/creativeStudioService.test.ts"],
    proofRefs: [],
    status: "DISABLED",
    remediationType: "CONNECT_SERVICE",
    lastVerifiedAt: SKILL_CATALOG_AUDITED_AT,
  }),
  defineSkill({
    skillId: "commercial_office",
    skillName: "Commercial Office",
    skillVersion: "1.0.0",
    description: "Bureau métier commercial — désactivé par défaut (config/services.json: enabled=false).",
    serviceScope: { type: "SINGLE_SERVICE", serviceId: "commercial_office" },
    capabilitiesProvided: ["commercial_office"],
    toolsRequired: ["src/services/commercialOfficeService.ts#CommercialOfficeService.handleTaskRequest"],
    dependencies: [],
    inputSchemaRef: "src/skills/builtin/commercialOffice.ts",
    outputSchemaRef: "src/orchestration/serviceOrchestrator.ts#OrchestrationResult",
    riskLevel: "MEDIUM",
    permissionLevel: "WRITE",
    sideEffects: true,
    idempotent: false,
    asyncSupported: false,
    timeoutMs: 60000,
    testRefs: ["src/services/commercialOfficeService.test.ts"],
    proofRefs: [],
    status: "DISABLED",
    remediationType: "CONNECT_SERVICE",
    lastVerifiedAt: SKILL_CATALOG_AUDITED_AT,
  }),
  defineSkill({
    skillId: "commercial_office_send",
    skillName: "Commercial Office — envoi",
    skillVersion: "1.0.0",
    description: "Action d'envoi du Commercial Office — exige explicitement la permission SEND (permissionByCapability), désactivé par défaut.",
    serviceScope: { type: "SINGLE_SERVICE", serviceId: "commercial_office" },
    capabilitiesProvided: ["commercial_office_send"],
    toolsRequired: ["src/email/emailProvider.ts#createEmailProvider"],
    dependencies: ["commercial_office"],
    inputSchemaRef: "src/skills/builtin/commercialOffice.ts#SEND_MESSAGE",
    outputSchemaRef: "src/orchestration/serviceOrchestrator.ts#OrchestrationResult",
    riskLevel: "MEDIUM",
    permissionLevel: "SEND",
    sideEffects: true,
    idempotent: false,
    asyncSupported: false,
    timeoutMs: 60000,
    testRefs: ["src/services/commercialOfficeService.test.ts"],
    proofRefs: [],
    status: "DISABLED",
    remediationType: "CONNECT_SERVICE",
    lastVerifiedAt: SKILL_CATALOG_AUDITED_AT,
  }),
  defineSkill({
    skillId: "marketing_office",
    skillName: "Marketing Office",
    skillVersion: "1.0.0",
    description: "Bureau métier marketing — désactivé par défaut (config/services.json: enabled=false).",
    serviceScope: { type: "SINGLE_SERVICE", serviceId: "marketing_office" },
    capabilitiesProvided: ["marketing_office"],
    toolsRequired: ["src/services/marketingOfficeService.ts#MarketingOfficeService.handleTaskRequest"],
    dependencies: [],
    inputSchemaRef: "src/skills/builtin/marketingOffice.ts",
    outputSchemaRef: "src/orchestration/serviceOrchestrator.ts#OrchestrationResult",
    riskLevel: "LOW",
    permissionLevel: "READ",
    sideEffects: true,
    idempotent: false,
    asyncSupported: false,
    timeoutMs: 60000,
    testRefs: ["src/services/marketingOfficeService.test.ts"],
    proofRefs: [],
    status: "DISABLED",
    remediationType: "CONNECT_SERVICE",
    lastVerifiedAt: SKILL_CATALOG_AUDITED_AT,
  }),

  // --- Gaps réels identifiés par l'audit (Phase 12) : le "tool" existe et est testé isolément,
  // aucun skill ne l'expose encore à l'agent. MISSING honnête, pas AVAILABLE. ---
  defineSkill({
    skillId: "read_ci_status",
    skillName: "Lecture du statut CI (non câblé)",
    skillVersion: "0.0.0",
    description: "githubReadOnlyClient.getCiStatus() existe et est testé isolément (githubReadOnlyClient.test.ts) mais AUCUN skill ne l'expose à l'agent — zéro appelant en production trouvé à l'audit. Gap réel, pas une supposition.",
    serviceScope: { type: "TRANSVERSAL" },
    capabilitiesProvided: ["read_ci_status"],
    toolsRequired: ["src/repository/githubReadOnlyClient.ts#getCiStatus"],
    dependencies: [],
    inputSchemaRef: "src/repository/githubReadOnlyClient.ts#RepoRef",
    outputSchemaRef: "src/repository/githubReadOnlyClient.ts#CiStatusResult",
    riskLevel: "LOW",
    permissionLevel: "READ",
    sideEffects: false,
    idempotent: true,
    asyncSupported: false,
    timeoutMs: 15000,
    probeId: "probe.read_ci_status.known_sha",
    testRefs: ["src/repository/githubReadOnlyClient.test.ts"],
    proofRefs: [],
    status: "MISSING",
    remediationType: "CREATE_SKILL",
    lastVerifiedAt: SKILL_CATALOG_AUDITED_AT,
  }),
  defineSkill({
    skillId: "read_main_protection",
    skillName: "Lecture de la protection de branche (non câblée)",
    skillVersion: "0.0.0",
    description: "githubReadOnlyClient.getMainProtectionStatus() existe et est testé isolément mais AUCUN skill ne l'expose à l'agent — zéro appelant en production trouvé à l'audit. Gap réel, pas une supposition.",
    serviceScope: { type: "TRANSVERSAL" },
    capabilitiesProvided: ["read_main_protection"],
    toolsRequired: ["src/repository/githubReadOnlyClient.ts#getMainProtectionStatus"],
    dependencies: [],
    inputSchemaRef: "src/repository/githubReadOnlyClient.ts#RepoRef",
    outputSchemaRef: "src/repository/githubReadOnlyClient.ts#MainProtectionResult",
    riskLevel: "LOW",
    permissionLevel: "READ",
    sideEffects: false,
    idempotent: true,
    asyncSupported: false,
    timeoutMs: 15000,
    probeId: "probe.read_main_protection.branch",
    testRefs: ["src/repository/githubReadOnlyClient.test.ts"],
    proofRefs: [],
    status: "MISSING",
    remediationType: "CREATE_SKILL",
    lastVerifiedAt: SKILL_CATALOG_AUDITED_AT,
  }),
]);
