import test,{beforeEach} from "node:test";import assert from "node:assert/strict";import {mkdtempSync} from "node:fs";import {tmpdir} from "node:os";import {join} from "node:path";import {closeDb,getDb} from "../persistence/db.js";import {config} from "../config.js";import {OperationStore} from "./operationStore.js";import {ArtifactStore} from "../workspaces/artifactStore.js";import {WorkspaceStore} from "../workspaces/workspaceStore.js";import {ActivityStore} from "../observability/activityStore.js";
import {ServiceRegistry} from "./serviceRegistry.js";import {ServiceOrchestrator} from "./serviceOrchestrator.js";import {Planner,type PlanStepSpec} from "../planning/planner.js";import {PlanRunner} from "../planning/planRunner.js";import {BackgroundRunner} from "../autonomy/backgroundRunner.js";import {SpecialistRegistry} from "./specialistRegistry.js";import type {ServiceAdapter} from "./serviceAdapter.js";import type {TaskRequest,ServiceEvent} from "./contract.js";
beforeEach(()=>{closeDb();config.db.path=":memory:";getDb();});
const operation=(store:OperationStore,id:string,created:number)=>{store.createOperation({taskId:id,traceId:`trace-${id}`,idempotencyKey:`key-${id}`,objective:id,capability:"cap",selectedService:"svc",status:"QUEUED",executionMode:"background",queuedAt:created});getDb().prepare("UPDATE service_operations SET created_at=?,queued_at=? WHERE task_id=?").run(created,created,id);store.setDispatchRequest(id,{schema_version:"1.0",task_id:id,trace_id:`trace-${id}`,idempotency_key:`key-${id}`,capability:"cap",objective:id,context:{},constraints:[],priority:"medium",permissions:[]},true);};
test("agentic serial FIFO uses insertion order when timestamps tie",()=>{const store=new OperationStore();operation(store,"z-first",1);operation(store,"a-second",1);assert.equal(store.claimNextBackground(false)?.operation.taskId,"z-first");});
test("retry_count increments only for an actual retry",()=>{const store=new OperationStore();store.createOperation({taskId:"retry",traceId:"t",idempotencyKey:"i",objective:"o",capability:"c",selectedService:"s",status:"FAILED",error:"TRANSPORT",executionMode:"foreground"});assert.equal(store.getOperation("retry")?.retryCount,0);assert.equal(store.updateStatus("retry","DISPATCHING"),true);assert.equal(store.getOperation("retry")?.retryCount,1);assert.equal(store.getOperation("retry")?.retryCount,1);});
test("artifact dedupe is atomic and conflicting content fails closed",()=>{const files=new WorkspaceStore(mkdtempSync(join(tmpdir(),"agentic-"))),workspace=files.create({name:"p",ownerType:"PLAN_RUN",ownerId:"p"}),artifacts=new ArtifactStore(files);const input={workspaceId:workspace.id,dedupeKey:"plan:p:final-result",name:"mission-result.json",content:"one"};artifacts.createTextArtifact(input);assert.throws(()=>artifacts.createTextArtifact({...input,content:"two"}));assert.equal(artifacts.listByWorkspace(workspace.id).length,1);});
test("activity is deduplicated, filtered, bounded and rejects secrets",()=>{const activity=new ActivityStore();activity.append({dedupeKey:"plan-created:p",planRunId:"p",eventType:"PLAN_CREATED",message:"Mission created"});activity.append({dedupeKey:"plan-created:p",planRunId:"p",eventType:"PLAN_CREATED",message:"Mission created"});assert.equal(activity.list({planRunId:"p",limit:999}).length,1);assert.throws(()=>activity.append({eventType:"PLAN_STARTED",message:"Authorization bearer secret"}));assert.throws(()=>activity.append({eventType:"PLAN_STARTED",message:"ok",metadata:{bad:undefined}}));});

const step=(id:string,capability="deep_research",depends_on:string[]=[]):PlanStepSpec=>({local_id:id,title:id,capability,objective:id,context:{},constraints:[],priority:"medium",depends_on});
const terminal=(r:TaskRequest):ServiceEvent[]=>[{schema_version:"1.0",event_id:`${r.task_id}-ok`,task_id:r.task_id,trace_id:r.trace_id,service:"research_service",sequence:1,type:"TASK_COMPLETED",timestamp:Date.now(),payload:{result:r.objective}}];
test("two plan research handlers execute truly in parallel and peak is real",async()=>{const registry=new ServiceRegistry("/missing");registry.register({id:"research_service",name:"research",enabled:true,transport:"local",endpoint:"research_service",auth:{type:"none"},capabilities:["deep_research"],parallelSafeCapabilities:["deep_research"],priority:1});let entered=0;let release!:()=>void;const gate=new Promise<void>(resolve=>release=resolve);const adapter={dispatchTask:async(_service:unknown,r:TaskRequest)=>{entered++;await gate;return{success:true as const,events:terminal(r),transportDurationMs:1}}} as ServiceAdapter;const orchestrator=new ServiceOrchestrator({registry,adapter}),planner=new Planner(),specialistFile=join(mkdtempSync(join(tmpdir(),"specialists-")),"specialists.json");await import("node:fs").then(fs=>fs.writeFileSync(specialistFile,JSON.stringify([{id:"research",name:"Research",enabled:true,priority:1,allowedCapabilities:["deep_research"],maxConcurrency:2}])));const runner=new PlanRunner(orchestrator,planner,undefined,500,new SpecialistRegistry(specialistFile,registry));const run=planner.createExecutionPlan("parallel",[step("a"),step("b")],registry,2,2);await runner.tick();const background=new BackgroundRunner(orchestrator,undefined,500,2);await background.tick();for(let i=0;i<20&&entered<2;i++)await new Promise(resolve=>setImmediate(resolve));assert.equal(entered,2);assert.equal(new (await import("../observability/observabilityStore.js")).ObservabilityStore().plan(run.id)?.peakParallelism,2);release();await background.tick();});

test("worker exception fails closed and the next serial operation continues",async()=>{const registry=new ServiceRegistry("/missing");registry.register({id:"svc",name:"svc",enabled:true,transport:"local",endpoint:"svc",auth:{type:"none"},capabilities:["cap"],parallelSafeCapabilities:[],priority:1});const orchestrator=new ServiceOrchestrator({registry,adapter:{dispatchTask:async()=>{throw new Error("boom")}} as unknown as ServiceAdapter});operation(orchestrator.store,"first",1);operation(orchestrator.store,"second",2);let calls=0;(orchestrator as any).executeClaimed=async(r:TaskRequest)=>{calls++;if(calls===1)throw new Error("boom");orchestrator.store.updateStatus(r.task_id,"COMPLETED","ok");return orchestrator.store.getOperation(r.task_id);};const runner=new BackgroundRunner(orchestrator);await runner.tick();assert.equal(orchestrator.store.getOperation("first")?.error,"WORKER_EXECUTION_EXCEPTION_STATE_UNKNOWN");await runner.tick();assert.equal(orchestrator.store.getOperation("second")?.status,"COMPLETED");assert.equal(calls,2);});
