import test,{beforeEach} from "node:test";import assert from "node:assert/strict";import {mkdtempSync} from "node:fs";import {tmpdir} from "node:os";import {join} from "node:path";import {closeDb,getDb} from "../persistence/db.js";import {config} from "../config.js";import {OperationStore} from "./operationStore.js";import {ArtifactStore} from "../workspaces/artifactStore.js";import {WorkspaceStore} from "../workspaces/workspaceStore.js";import {ActivityStore} from "../observability/activityStore.js";
import {ServiceRegistry} from "./serviceRegistry.js";import {ServiceOrchestrator} from "./serviceOrchestrator.js";import {Planner,type PlanStepSpec} from "../planning/planner.js";import {PlanRunner} from "../planning/planRunner.js";import {BackgroundRunner} from "../autonomy/backgroundRunner.js";import {SpecialistRegistry} from "./specialistRegistry.js";import type {ServiceAdapter} from "./serviceAdapter.js";import type {TaskRequest,ServiceEvent} from "./contract.js";
import {writeFileSync} from "node:fs";import type {ReplanningEngine} from "../planning/replanningEngine.js";import {MissionConsolidator} from "../planning/missionConsolidator.js";import {ObservabilityStore} from "../observability/observabilityStore.js";
beforeEach(()=>{closeDb();config.db.path=":memory:";getDb();});
const operation=(store:OperationStore,id:string,created:number)=>{store.createOperation({taskId:id,traceId:`trace-${id}`,idempotencyKey:`key-${id}`,objective:id,capability:"cap",selectedService:"svc",status:"QUEUED",executionMode:"background",queuedAt:created});getDb().prepare("UPDATE service_operations SET created_at=?,queued_at=? WHERE task_id=?").run(created,created,id);store.setDispatchRequest(id,{schema_version:"1.0",task_id:id,trace_id:`trace-${id}`,idempotency_key:`key-${id}`,capability:"cap",objective:id,context:{},constraints:[],priority:"medium",permissions:[]},true);};
test("agentic serial FIFO uses insertion order when timestamps tie",()=>{const store=new OperationStore();operation(store,"z-first",1);operation(store,"a-second",1);assert.equal(store.claimNextBackground(false)?.operation.taskId,"z-first");});
test("retry_count increments only for an actual retry",()=>{const store=new OperationStore();store.createOperation({taskId:"retry",traceId:"t",idempotencyKey:"i",objective:"o",capability:"c",selectedService:"s",status:"FAILED",error:"TRANSPORT",executionMode:"foreground"});assert.equal(store.getOperation("retry")?.retryCount,0);assert.equal(store.updateStatus("retry","DISPATCHING"),true);assert.equal(store.getOperation("retry")?.retryCount,1);assert.equal(store.getOperation("retry")?.retryCount,1);});
test("artifact dedupe is atomic and conflicting content fails closed",()=>{const files=new WorkspaceStore(mkdtempSync(join(tmpdir(),"agentic-"))),workspace=files.create({name:"p",ownerType:"PLAN_RUN",ownerId:"p"}),artifacts=new ArtifactStore(files);const input={workspaceId:workspace.id,dedupeKey:"plan:p:final-result",name:"mission-result.json",content:"one"};artifacts.createTextArtifact(input);assert.throws(()=>artifacts.createTextArtifact({...input,content:"two"}));assert.equal(artifacts.listByWorkspace(workspace.id).length,1);});
test("activity is deduplicated, filtered, bounded and rejects secrets",()=>{const activity=new ActivityStore();activity.append({dedupeKey:"plan-created:p",planRunId:"p",eventType:"PLAN_CREATED",message:"Mission created"});activity.append({dedupeKey:"plan-created:p",planRunId:"p",eventType:"PLAN_CREATED",message:"Mission created"});assert.equal(activity.list({planRunId:"p",limit:999}).length,1);assert.throws(()=>activity.append({eventType:"PLAN_STARTED",message:"Authorization bearer secret"}));assert.throws(()=>activity.append({eventType:"PLAN_STARTED",message:"ok",metadata:{bad:undefined}}));});

const step=(id:string,capability="deep_research",depends_on:string[]=[]):PlanStepSpec=>({local_id:id,title:id,capability,objective:id,context:{},constraints:[],priority:"medium",depends_on});
const terminal=(r:TaskRequest):ServiceEvent[]=>[{schema_version:"1.0",event_id:`${r.task_id}-ok`,task_id:r.task_id,trace_id:r.trace_id,service:"research_service",sequence:1,type:"TASK_COMPLETED",timestamp:Date.now(),payload:{result:r.objective}}];
test("two plan research handlers execute truly in parallel and peak is real",async()=>{const registry=new ServiceRegistry("/missing");registry.register({id:"research_service",name:"research",enabled:true,transport:"local",endpoint:"research_service",auth:{type:"none"},capabilities:["deep_research"],parallelSafeCapabilities:["deep_research"],priority:1});let entered=0;let release!:()=>void;const gate=new Promise<void>(resolve=>release=resolve);const adapter={dispatchTask:async(_service:unknown,r:TaskRequest)=>{entered++;await gate;return{success:true as const,events:terminal(r),transportDurationMs:1}}} as ServiceAdapter;const orchestrator=new ServiceOrchestrator({registry,adapter}),planner=new Planner(),specialistFile=join(mkdtempSync(join(tmpdir(),"specialists-")),"specialists.json");await import("node:fs").then(fs=>fs.writeFileSync(specialistFile,JSON.stringify([{id:"research",name:"Research",enabled:true,priority:1,allowedCapabilities:["deep_research"],maxConcurrency:2}])));const runner=new PlanRunner(orchestrator,planner,undefined,500,new SpecialistRegistry(specialistFile,registry));const run=planner.createExecutionPlan("parallel",[step("a"),step("b")],registry,2,2);await runner.tick();const background=new BackgroundRunner(orchestrator,undefined,500,2);await background.tick();for(let i=0;i<20&&entered<2;i++)await new Promise(resolve=>setImmediate(resolve));assert.equal(entered,2);assert.equal(new (await import("../observability/observabilityStore.js")).ObservabilityStore().plan(run.id)?.peakParallelism,2);release();await background.tick();});

test("worker exception fails closed and the next serial operation continues",async()=>{const registry=new ServiceRegistry("/missing");registry.register({id:"svc",name:"svc",enabled:true,transport:"local",endpoint:"svc",auth:{type:"none"},capabilities:["cap"],parallelSafeCapabilities:[],priority:1});const orchestrator=new ServiceOrchestrator({registry,adapter:{dispatchTask:async()=>{throw new Error("boom")}} as unknown as ServiceAdapter});operation(orchestrator.store,"first",1);operation(orchestrator.store,"second",2);let calls=0;(orchestrator as any).executeClaimed=async(r:TaskRequest)=>{calls++;if(calls===1)throw new Error("boom");orchestrator.store.updateStatus(r.task_id,"COMPLETED","ok");return orchestrator.store.getOperation(r.task_id);};const runner=new BackgroundRunner(orchestrator);await runner.tick();assert.equal(orchestrator.store.getOperation("first")?.error,"WORKER_EXECUTION_EXCEPTION_STATE_UNKNOWN");await runner.tick();assert.equal(orchestrator.store.getOperation("second")?.status,"COMPLETED");assert.equal(calls,2);});

type Deferred={promise:Promise<void>;resolve:()=>void};
const deferred=():Deferred=>{let resolve!:()=>void;return{promise:new Promise<void>(done=>resolve=done),resolve};};
const waitFor=async(check:()=>boolean)=>{for(let i=0;i<100&&!check();i++)await new Promise(resolve=>setImmediate(resolve));assert.ok(check(),"condition was not reached");};
function agenticRegistry(){const registry=new ServiceRegistry("/missing");registry.register({id:"research_service",name:"Research",enabled:true,transport:"local",endpoint:"research_service",auth:{type:"none"},capabilities:["deep_research"],parallelSafeCapabilities:["deep_research"],priority:3});registry.register({id:"software_factory",name:"Software",enabled:true,transport:"local",endpoint:"software_factory",auth:{type:"none"},capabilities:["software_development"],parallelSafeCapabilities:[],priority:2});registry.register({id:"workspace_service",name:"Workspace",enabled:true,transport:"local",endpoint:"workspace_service",auth:{type:"none"},capabilities:["file_management"],parallelSafeCapabilities:[],priority:1});return registry;}
function specialists(registry:ServiceRegistry,researchMax=2){const file=join(mkdtempSync(join(tmpdir(),"agentic-specialists-")),"specialists.json");writeFileSync(file,JSON.stringify([{id:"research",name:"Research",enabled:true,priority:3,allowedCapabilities:["deep_research"],maxConcurrency:researchMax},{id:"software",name:"Software",enabled:true,priority:2,allowedCapabilities:["software_development"],maxConcurrency:1},{id:"workspace",name:"Workspace",enabled:true,priority:1,allowedCapabilities:["file_management"],maxConcurrency:1}]));return new SpecialistRegistry(file,registry);}
function completed(request:TaskRequest,service:string):ServiceEvent[]{return[{schema_version:"1.0",event_id:`${request.task_id}-completed`,task_id:request.task_id,trace_id:request.trace_id,service,sequence:1,type:"TASK_COMPLETED",timestamp:Date.now(),payload:{result:request.objective}}];}
function failed(request:TaskRequest):ServiceEvent[]{return[{schema_version:"1.0",event_id:`${request.task_id}-failed`,task_id:request.task_id,trace_id:request.trace_id,service:"research_service",sequence:1,type:"TASK_FAILED",timestamp:Date.now(),payload:{error:"safe failure",replannable:true,side_effect_state:"none"}}];}

test("specialist maxConcurrency=2 runs a third research only after the first pair",async()=>{const registry=agenticRegistry(),gates=[deferred(),deferred(),deferred()];let entered=0,active=0,maximum=0;const adapter={dispatchTask:async(_s:unknown,r:TaskRequest)=>{const index=entered++;active++;maximum=Math.max(maximum,active);await gates[index].promise;active--;return{success:true as const,events:completed(r,"research_service"),transportDurationMs:1};}} as ServiceAdapter;const orchestrator=new ServiceOrchestrator({registry,adapter}),planner=new Planner(),planRunner=new PlanRunner(orchestrator,planner,undefined,500,specialists(registry,2)),background=new BackgroundRunner(orchestrator,undefined,500,3);planner.createExecutionPlan("three",[step("a"),step("b"),step("c")],registry,2,3);await planRunner.tick();await background.tick();await waitFor(()=>entered===2);assert.equal(maximum,2);assert.equal(orchestrator.store.listOperations().length,2);gates[0].resolve();gates[1].resolve();await background.tick();await planRunner.tick();assert.equal(orchestrator.store.listOperations().length,3);const third=background.tick();await waitFor(()=>entered===3);assert.equal(maximum,2);gates[2].resolve();await third;});

for(const capability of ["software_development","file_management"]){test(`${capability} operations remain strictly serial`,async()=>{const registry=agenticRegistry(),gates=[deferred(),deferred()];let entered=0,active=0,maximum=0;const service=capability==="software_development"?"software_factory":"workspace_service";const adapter={dispatchTask:async(_s:unknown,r:TaskRequest)=>{const index=entered++;active++;maximum=Math.max(maximum,active);await gates[index].promise;active--;return{success:true as const,events:completed(r,service),transportDurationMs:1};}} as ServiceAdapter;const orchestrator=new ServiceOrchestrator({registry,adapter}),planner=new Planner(),planRunner=new PlanRunner(orchestrator,planner,undefined,500,specialists(registry)),background=new BackgroundRunner(orchestrator,undefined,500,3);planner.createExecutionPlan("serial",[step("a",capability),step("b",capability)],registry,2,3);await planRunner.tick();const first=background.tick();await waitFor(()=>entered===1);assert.equal(orchestrator.store.listOperations().length,1);gates[0].resolve();await first;await planRunner.tick();const second=background.tick();await waitFor(()=>entered===2);assert.equal(maximum,1);gates[1].resolve();await second;});}

test("mixed plan runs research together, then software alone",async()=>{const registry=agenticRegistry(),researchGate=deferred(),softwareGate=deferred();let researchEntered=0,softwareEntered=0,active=0,maximum=0;const adapter={dispatchTask:async(_s:unknown,r:TaskRequest)=>{active++;maximum=Math.max(maximum,active);if(r.capability==="deep_research"){researchEntered++;await researchGate.promise;}else{softwareEntered++;assert.equal(researchEntered,2);await softwareGate.promise;}active--;return{success:true as const,events:completed(r,r.capability==="deep_research"?"research_service":"software_factory"),transportDurationMs:1};}} as ServiceAdapter;const orchestrator=new ServiceOrchestrator({registry,adapter}),planner=new Planner(),planRunner=new PlanRunner(orchestrator,planner,undefined,500,specialists(registry)),background=new BackgroundRunner(orchestrator,undefined,500,3);planner.createExecutionPlan("mixed",[step("a"),step("b"),step("c","software_development",["a","b"])],registry,2,3);await planRunner.tick();await background.tick();await waitFor(()=>researchEntered===2);assert.equal(softwareEntered,0);researchGate.resolve();await background.tick();await planRunner.tick();const software=background.tick();await waitFor(()=>softwareEntered===1);assert.equal(active,1);assert.equal(maximum,2);softwareGate.resolve();await software;});

test("an active serial operation prevents dispatch of ready parallel research",async()=>{const registry=agenticRegistry(),serialGate=deferred();let researchEntered=0;const adapter={dispatchTask:async(_s:unknown,r:TaskRequest)=>{if(r.capability==="software_development")await serialGate.promise;else researchEntered++;return{success:true as const,events:completed(r,r.capability==="deep_research"?"research_service":"software_factory"),transportDurationMs:1};}} as ServiceAdapter;const orchestrator=new ServiceOrchestrator({registry,adapter}),planner=new Planner(),planRunner=new PlanRunner(orchestrator,planner,undefined,500,specialists(registry)),background=new BackgroundRunner(orchestrator,undefined,500,3),run=planner.createExecutionPlan("lane",[step("a","software_development"),step("b")],registry,2,3);await planRunner.tick();const serial=background.tick();await waitFor(()=>orchestrator.store.listOperations()[0]?.status==="DISPATCHING");await planRunner.tick();assert.equal(planner.nodes(run.id).find(n=>n.title==="b")?.status,"pending");assert.equal(orchestrator.store.listOperations().length,1);assert.equal(researchEntered,0);serialGate.resolve();await serial;await planRunner.tick();assert.equal(orchestrator.store.listOperations().length,2);});

test("safe failure freezes independent dispatch until active peer settles and then replans",async()=>{const registry=agenticRegistry(),aGate=deferred(),bGate=deferred();const adapter={dispatchTask:async(_s:unknown,r:TaskRequest)=>{if(r.objective==="a"){await aGate.promise;return{success:true as const,events:failed(r),transportDurationMs:1};}await bGate.promise;return{success:true as const,events:completed(r,"research_service"),transportDurationMs:1};}} as ServiceAdapter;const orchestrator=new ServiceOrchestrator({registry,adapter}),planner=new Planner();let replanCalls=0;const replanning={propose:async()=>{replanCalls++;return[step("a2")];}} as unknown as ReplanningEngine;const planRunner=new PlanRunner(orchestrator,planner,replanning,500,specialists(registry,2)),background=new BackgroundRunner(orchestrator,undefined,500,2),run=planner.createExecutionPlan("freeze",[step("a"),step("b"),step("d")],registry,2,3);await planRunner.tick();await background.tick();aGate.resolve();await waitFor(()=>orchestrator.store.listOperations().some(op=>op.objective==="a"&&op.status==="FAILED"));await planRunner.tick();assert.ok(planner.getRun(run.id)?.pendingReplanNodeId);assert.equal(planner.nodes(run.id).find(n=>n.title==="d")?.status,"pending");assert.equal(orchestrator.store.listOperations().some(op=>op.objective==="d"),false);assert.equal(replanCalls,0);bGate.resolve();await waitFor(()=>orchestrator.store.listOperations().some(op=>op.objective==="b"&&op.status==="COMPLETED"));await planRunner.tick();assert.equal(replanCalls,1);assert.equal(planner.getRun(run.id)?.pendingReplanNodeId,undefined);assert.equal(planner.getRun(run.id)?.generation,2);});

test("persisted pending replan survives restart and is applied exactly once",async()=>{const registry=agenticRegistry(),orchestrator=new ServiceOrchestrator({registry}),planner=new Planner(),run=planner.createExecutionPlan("restart",[step("a"),step("d")],registry,2,2),failedNode=planner.nodes(run.id).find(n=>n.title==="a")!;getDb().prepare("UPDATE plan_nodes SET status='failed',error='safe' WHERE id=?").run(failedNode.id);getDb().prepare("UPDATE plan_runs SET status='RUNNING',pending_replan_node_id=? WHERE id=?").run(failedNode.id,run.id);assert.equal(planner.getRun(run.id)?.pendingReplanNodeId,failedNode.id);let calls=0;const replanning={propose:async()=>{calls++;assert.equal(planner.getRun(run.id)?.pendingReplanNodeId,failedNode.id);return[step("a2")];}} as unknown as ReplanningEngine;const restarted=new PlanRunner(orchestrator,planner,replanning,500,specialists(registry));await restarted.tick();assert.equal(calls,1);assert.equal(planner.getRun(run.id)?.generation,2);assert.equal(planner.getRun(run.id)?.replanCount,1);assert.equal(planner.getRun(run.id)?.pendingReplanNodeId,undefined);assert.equal(orchestrator.store.listOperations().length,0);assert.equal(planner.nodes(run.id).filter(n=>n.generation===2).length,1);});

test("two safe parallel failures block without invoking replanning",async()=>{const registry=agenticRegistry(),gate=deferred();let entered=0;const adapter={dispatchTask:async(_s:unknown,r:TaskRequest)=>{entered++;await gate.promise;return{success:true as const,events:failed(r),transportDurationMs:1};}} as ServiceAdapter;const orchestrator=new ServiceOrchestrator({registry,adapter}),planner=new Planner();let calls=0;const replanning={propose:async()=>{calls++;return[step("replacement")];}} as unknown as ReplanningEngine;const planRunner=new PlanRunner(orchestrator,planner,replanning,500,specialists(registry)),background=new BackgroundRunner(orchestrator,undefined,500,2),run=planner.createExecutionPlan("double failure",[step("a"),step("b")],registry,2,2);await planRunner.tick();await background.tick();await waitFor(()=>entered===2);gate.resolve();await background.tick();await planRunner.tick();assert.equal(planner.getRun(run.id)?.status,"BLOCKED");assert.equal(planner.getRun(run.id)?.lastError,"MULTIPLE_PARALLEL_FAILURES");assert.equal(calls,0);});

test("real peak remains one when the background pool limit is one",async()=>{const registry=agenticRegistry(),gates=[deferred(),deferred(),deferred()];let entered=0,active=0,maximum=0;const adapter={dispatchTask:async(_s:unknown,r:TaskRequest)=>{const index=entered++;active++;maximum=Math.max(maximum,active);await gates[index].promise;active--;return{success:true as const,events:completed(r,"research_service"),transportDurationMs:1};}} as ServiceAdapter;const orchestrator=new ServiceOrchestrator({registry,adapter}),planner=new Planner(),run=planner.createExecutionPlan("peak one",[step("a"),step("b"),step("c")],registry,2,3);for(const node of planner.nodes(run.id))await orchestrator.dispatchCapability({action:"DISPATCH_CAPABILITY",capability:"deep_research",objective:node.title},{executionMode:"background",planRunId:run.id,planNodeId:node.id,parallelAllowed:true});const background=new BackgroundRunner(orchestrator,undefined,500,1);await background.tick();await waitFor(()=>entered===1);assert.equal(new ObservabilityStore().plan(run.id)?.peakParallelism,1);for(let i=0;i<3;i++){gates[i].resolve();await background.tick();}assert.equal(maximum,1);assert.equal(new ObservabilityStore().plan(run.id)?.peakParallelism,1);});

test("consolidation recovery reuses exactly one artifact for each stable dedupe key",()=>{const registry=agenticRegistry(),orchestrator=new ServiceOrchestrator({registry}),planner=new Planner(),run=planner.createExecutionPlan("consolidate",[step("a")],registry),node=planner.nodes(run.id)[0];getDb().prepare("UPDATE plan_nodes SET status='done',result='fact' WHERE id=?").run(node.id);new MissionConsolidator(orchestrator.artifacts).consolidate(run,planner.nodes(run.id));new MissionConsolidator(orchestrator.artifacts).consolidate(run,planner.nodes(run.id));const artifacts=orchestrator.artifacts.listByWorkspace(run.workspaceId!);assert.equal(artifacts.filter(a=>a.name==="mission-result.json").length,1);assert.equal(artifacts.filter(a=>a.name==="mission-report.md").length,1);const rows=getDb().prepare("SELECT dedupe_key FROM artifacts WHERE plan_run_id=?").all(run.id) as Array<{dedupe_key:string}>;assert.deepEqual(new Set(rows.map(r=>r.dedupe_key)).size,2);});
