import type {TaskRequest,ServiceEvent} from "./contract.js";import type {ServiceDefinition} from "./serviceRegistry.js";import {SoftwareFactoryService} from "../services/softwareFactoryService.js";
export interface LocalTaskService{handleTaskRequest(r:TaskRequest):Promise<ServiceEvent[]>;health?():Promise<Record<string,unknown>>|Record<string,unknown>}
export type ServiceAdapterResponse=({success:true;events:ServiceEvent[]}|{success:false;transportError:true;message:string})&{transportDurationMs:number};
export class ServiceAdapter{private localSoftwareFactory:LocalTaskService=new SoftwareFactoryService();private local=new Map<string,LocalTaskService>();constructor(){this.registerLocal("software_factory",this.localSoftwareFactory);}registerLocal(id:string,s:LocalTaskService){this.local.set(id,s);}
 private definition(value:ServiceDefinition|string):ServiceDefinition{return typeof value==="string"?{id:"software_factory",name:"Software Factory",enabled:true,transport:["local","direct","in-process"].includes(value)?"local":"task_http",endpoint:value,capabilities:["software_development"],priority:0,riskByCapability:{software_development:"MEDIUM"},auth:{type:"bearer_env",envVar:"SOFTWARE_FACTORY_TOKEN"}}:value;}
 private headers(s:ServiceDefinition):Record<string,string>{const h:{[k:string]:string}={"content-type":"application/json"};if(s.auth.type==="bearer_env"){const token=process.env[s.auth.envVar]||(s.id==="software_factory"?process.env.API_TOKEN:undefined);if(!token)throw new Error(`AUTH_ENV_MISSING: ${s.auth.envVar}`);h.authorization=`Bearer ${token}`;}return h;}
 async checkHealth(value:ServiceDefinition|string,timeoutMs?:number){const started=Date.now(),s=this.definition(value),checkedAt=new Date().toISOString();if(s.transport==="local"){const reachable=this.local.has(s.id);return{reachable,authenticated:true,status:reachable?200:"not_registered",latencyMs:Date.now()-started,checkedAt};}try{const c=new AbortController(),t=setTimeout(()=>c.abort(),timeoutMs??s.healthTimeoutMs??5000);const res=await fetch(`${s.endpoint.replace(/\/+$/,'')}${s.healthPath??'/health'}`,{headers:this.headers(s),signal:c.signal});clearTimeout(t);return{reachable:res.ok,authenticated:res.status!==401&&res.status!==403,status:res.status,latencyMs:Date.now()-started,checkedAt};}catch(e){return{reachable:false,authenticated:false,status:"ERROR",latencyMs:Date.now()-started,checkedAt,errorCode:(e as Error).name==="AbortError"?"CONNECTION_TIMEOUT":"CONNECTION_FAILED"};}}
 async dispatchTask(value:ServiceDefinition|string,r:TaskRequest,timeoutMs?:number):Promise<ServiceAdapterResponse>{const started=Date.now(),s=this.definition(value),effectiveTimeout=timeoutMs??s.requestTimeoutMs??5000;if(s.transport==="local"){const target=s.id==="software_factory"?this.localSoftwareFactory:this.local.get(s.id);if(!target)return{success:false,transportError:true,message:`LOCAL_SERVICE_NOT_REGISTERED: ${s.id}`,transportDurationMs:Date.now()-started};try{return{success:true,events:await target.handleTaskRequest(r),transportDurationMs:Date.now()-started}}catch(e){return{success:false,transportError:true,message:(e as Error).message,transportDurationMs:Date.now()-started};}}try{const c=new AbortController(),t=setTimeout(()=>c.abort(),effectiveTimeout),res=await fetch(`${s.endpoint.replace(/\/+$/,'')}${s.taskPath??'/tasks'}`,{method:"POST",headers:this.headers(s),body:JSON.stringify(r),signal:c.signal});clearTimeout(t);if(!res.ok)return{success:false,transportError:true,message:`HTTP error ${res.status}`,transportDurationMs:Date.now()-started};const d=await res.json() as any;return{success:true,events:Array.isArray(d)?d:d.events??[],transportDurationMs:Date.now()-started};}catch(e){const error=e as Error;return{success:false,transportError:true,message:error.name==="AbortError"?`Network timeout after ${effectiveTimeout}ms`:`Transport error: ${error.message}`,transportDurationMs:Date.now()-started};}}
}
