import {readFileSync,existsSync} from "node:fs";import {join} from "node:path";import type {RiskLevel} from "./contract.js";import {ServiceConnectionStore,type ServiceConnectionOverride} from "./serviceConnectionStore.js";
export type ServiceTransport="local"|"task_http";export type ServiceAuth={type:"none"}|{type:"bearer_env";envVar:string};export type ServiceSource="FACTORY"|"DATABASE"|"ENVIRONMENT";
export interface ServiceDefinition{id:string;name:string;description?:string;enabled:boolean;transport:ServiceTransport;endpoint:string;capabilities:string[];parallelSafeCapabilities?:string[];priority:number;riskByCapability?:Record<string,RiskLevel>;auth:ServiceAuth;healthPath?:string;taskPath?:string;requestTimeoutMs?:number;healthTimeoutMs?:number;source?:ServiceSource}
const risks=new Set(["LOW","MEDIUM","HIGH","CRITICAL"]);const envName=/^[A-Z][A-Z0-9_]*$/;
export function riskForCapability(s:ServiceDefinition,c:string):RiskLevel|null{const r=s.riskByCapability?.[c]??"LOW";return risks.has(r)?r as RiskLevel:null;}
function path(value:unknown,fallback:string){const p=value??fallback;if(typeof p!=="string"||!p.startsWith("/")||p.includes("..")||p.includes("://"))throw new Error("invalid service path");return p;}
export function validateServiceDefinition(raw:unknown,strict=false):ServiceDefinition{if(!raw||typeof raw!=="object"||Array.isArray(raw))throw new Error("service must be an object");const r=raw as any,transport=r.transport??(["local","direct","in-process"].includes(r.endpoint)?"local":"task_http"),auth=r.auth??(r.id==="software_factory"?{type:"bearer_env",envVar:"SOFTWARE_FACTORY_TOKEN"}:{type:"none"});if(typeof r.id!=="string"||!r.id.trim()||typeof r.name!=="string"||!r.name.trim()||typeof r.enabled!=="boolean"||!Array.isArray(r.capabilities)||!r.capabilities.length||!r.capabilities.every((x:unknown)=>typeof x==="string"&&!!x.trim())||!Number.isFinite(r.priority)||r.priority<0||r.priority>100||!["local","task_http"].includes(transport))throw new Error("invalid required fields");const parallel=r.parallelSafeCapabilities??[];if(!Array.isArray(parallel)||!parallel.every((x:unknown)=>typeof x==="string"&&r.capabilities.includes(x)))throw new Error("invalid parallel safe capabilities");if(r.riskByCapability!==undefined&&(typeof r.riskByCapability!=="object"||strict&&Object.keys(r.riskByCapability).some(x=>!r.capabilities.includes(x))||(strict&&Object.values(r.riskByCapability).some(x=>!risks.has(x as string)))))throw new Error("invalid risks");if(transport==="local"&&typeof r.endpoint!=="string")r.endpoint=r.id;if(transport==="task_http"){let u:URL;try{u=new URL(r.endpoint);}catch{throw new Error("invalid endpoint");}if(!["http:","https:"].includes(u.protocol))throw new Error("invalid endpoint protocol");}if(!auth||!["none","bearer_env"].includes(auth.type)||(auth.type==="bearer_env"&&!envName.test(auth.envVar)))throw new Error("invalid auth");for(const n of [r.requestTimeoutMs,r.healthTimeoutMs])if(n!==undefined&&(!Number.isInteger(n)||n<100||n>120000))throw new Error("invalid timeout");return{...r,id:r.id.trim(),name:r.name.trim(),transport,auth,healthPath:path(r.healthPath,"/health"),taskPath:path(r.taskPath,"/tasks"),healthTimeoutMs:r.healthTimeoutMs??5000,parallelSafeCapabilities:[...new Set(parallel)]};}
export function resolveServiceEndpoint(s:ServiceDefinition):ServiceDefinition{let endpoint=s.endpoint,source=s.source;if(s.id==="software_factory"){if(process.env.SOFTWARE_FACTORY_URL){endpoint=process.env.SOFTWARE_FACTORY_URL;source="ENVIRONMENT";}else if(endpoint==="http://localhost:4000"&&(process.env.PORT||process.env.API_PORT)){endpoint=`http://localhost:${process.env.PORT||process.env.API_PORT}`;source="ENVIRONMENT";}}if(process.env.PORT&&endpoint.includes("${PORT}")){endpoint=endpoint.replace("${PORT}",process.env.PORT);source="ENVIRONMENT";}return{...s,endpoint,source,transport:s.id==="software_factory"&&["local","direct","in-process"].includes(endpoint)?"local":s.transport};}
const merge=(base:ServiceDefinition,o:ServiceConnectionOverride):ServiceDefinition=>validateServiceDefinition({...base,name:o.name??base.name,enabled:o.enabled??base.enabled,transport:o.transport??base.transport,endpoint:o.endpoint??base.endpoint,healthPath:o.healthPath??base.healthPath,taskPath:o.taskPath??base.taskPath,auth:o.auth??base.auth,priority:o.priority??base.priority,requestTimeoutMs:o.requestTimeoutMs??base.requestTimeoutMs,healthTimeoutMs:o.healthTimeoutMs??base.healthTimeoutMs,capabilities:o.capabilities??base.capabilities,parallelSafeCapabilities:o.parallelSafeCapabilities??base.parallelSafeCapabilities,riskByCapability:o.riskByCapability??base.riskByCapability,source:"DATABASE"},true);
export class ServiceRegistry{private services:ServiceDefinition[]=[];private factory:ServiceDefinition[]=[];readonly diagnostics:string[]=[];readonly connections=new ServiceConnectionStore();constructor(path?:string){const p=path||join(process.cwd(),"config/services.json");if(existsSync(p))try{const parsed=JSON.parse(readFileSync(p,"utf8"));if(!Array.isArray(parsed))throw new Error("root must be array");for(const raw of parsed)try{this.factory.push({...validateServiceDefinition(raw,true),source:"FACTORY"});}catch(e){this.diagnostics.push(`Invalid service ${(raw as any)?.id??"unknown"}: ${(e as Error).message}`);}}catch(e){this.diagnostics.push(`Invalid registry: ${(e as Error).message}`);}this.refresh();}
 refresh(){this.services=this.factory.map(x=>({...x}));for(const o of this.connections.list())try{const base=this.services.find(x=>x.id===o.serviceId);if(base)this.services=this.services.map(x=>x.id===o.serviceId?merge(x,o):x);else if(o.userCreated)this.services.push(validateServiceDefinition({id:o.serviceId,name:o.name,enabled:o.enabled??true,transport:o.transport,endpoint:o.endpoint,auth:o.auth,priority:o.priority,capabilities:o.capabilities,parallelSafeCapabilities:o.parallelSafeCapabilities,riskByCapability:o.riskByCapability,healthPath:o.healthPath,taskPath:o.taskPath,requestTimeoutMs:o.requestTimeoutMs,healthTimeoutMs:o.healthTimeoutMs,source:"DATABASE"},true));}catch(e){this.diagnostics.push(`Invalid override ${o.serviceId}: ${(e as Error).message}`);}}
 register(raw:ServiceDefinition){const s=validateServiceDefinition(raw);this.services=this.services.filter(x=>x.id!==s.id);this.services.push(s);}
 findServiceForCapability(c:string){return this.services.filter(s=>s.enabled&&s.capabilities.includes(c)).sort((a,b)=>b.priority-a.priority).map(resolveServiceEndpoint)[0]??null;}getServiceById(id:string){const s=this.services.find(x=>x.id===id);return s?resolveServiceEndpoint(s):null;}listServices(){return this.services.map(resolveServiceEndpoint);}knownCapabilities(){return [...new Set(this.factory.flatMap(s=>s.capabilities))];}
}
