import {getDb} from "../persistence/db.js";
import type {ServiceAuth,ServiceDefinition,ServiceTransport} from "./serviceRegistry.js";
export interface ServiceConnectionOverride {serviceId:string;name?:string;userCreated:boolean;enabled?:boolean;transport?:ServiceTransport;endpoint?:string;healthPath?:string;taskPath?:string;auth?:ServiceAuth;priority?:number;requestTimeoutMs?:number;healthTimeoutMs?:number;capabilities?:string[];parallelSafeCapabilities?:string[];riskByCapability?:ServiceDefinition["riskByCapability"];lastTestAt?:number;lastSuccessAt?:number;lastLatencyMs?:number;lastError?:string|null}
const parse=<T>(v:string|null):T|undefined=>v===null?undefined:JSON.parse(v) as T;
export class ServiceConnectionStore{
 list():ServiceConnectionOverride[]{return (getDb().prepare("SELECT * FROM service_connections").all() as any[]).map(r=>({serviceId:r.service_id,name:r.name??undefined,userCreated:Boolean(r.user_created),enabled:r.enabled_override===null?undefined:Boolean(r.enabled_override),transport:r.transport_override??undefined,endpoint:r.endpoint_override??undefined,healthPath:r.health_path??undefined,taskPath:r.task_path??undefined,auth:r.auth_type_override?(r.auth_type_override==="none"?{type:"none"}:{type:"bearer_env",envVar:r.auth_env_var}):undefined,priority:r.priority_override??undefined,requestTimeoutMs:r.request_timeout_ms??undefined,healthTimeoutMs:r.health_timeout_ms??undefined,capabilities:parse(r.capabilities_json),parallelSafeCapabilities:parse(r.parallel_safe_capabilities_json),riskByCapability:parse(r.risk_by_capability_json),lastTestAt:r.last_test_at??undefined,lastSuccessAt:r.last_success_at??undefined,lastLatencyMs:r.last_latency_ms??undefined,lastError:r.last_error??undefined}));}
 get(id:string){return this.list().find(x=>x.serviceId===id)??null;}
 save(v:ServiceConnectionOverride){getDb().prepare(`INSERT INTO service_connections(service_id,name,user_created,enabled_override,transport_override,endpoint_override,health_path,task_path,auth_type_override,auth_env_var,priority_override,request_timeout_ms,health_timeout_ms,capabilities_json,parallel_safe_capabilities_json,risk_by_capability_json,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?) ON CONFLICT(service_id) DO UPDATE SET name=excluded.name,user_created=excluded.user_created,enabled_override=excluded.enabled_override,transport_override=excluded.transport_override,endpoint_override=excluded.endpoint_override,health_path=excluded.health_path,task_path=excluded.task_path,auth_type_override=excluded.auth_type_override,auth_env_var=excluded.auth_env_var,priority_override=excluded.priority_override,request_timeout_ms=excluded.request_timeout_ms,health_timeout_ms=excluded.health_timeout_ms,capabilities_json=excluded.capabilities_json,parallel_safe_capabilities_json=excluded.parallel_safe_capabilities_json,risk_by_capability_json=excluded.risk_by_capability_json,updated_at=excluded.updated_at`).run(v.serviceId,v.name??null,v.userCreated?1:0,v.enabled===undefined?null:Number(v.enabled),v.transport??null,v.endpoint??null,v.healthPath??null,v.taskPath??null,v.auth?.type??null,v.auth?.type==="bearer_env"?v.auth.envVar:null,v.priority??null,v.requestTimeoutMs??null,v.healthTimeoutMs??null,v.capabilities===undefined?null:JSON.stringify(v.capabilities),v.parallelSafeCapabilities===undefined?null:JSON.stringify(v.parallelSafeCapabilities),v.riskByCapability===undefined?null:JSON.stringify(v.riskByCapability),Date.now());}
 reset(id:string){getDb().prepare("DELETE FROM service_connections WHERE service_id=?").run(id);}
 recordDiagnostic(id:string,d:{success:boolean;latencyMs:number;error?:string}){const now=Date.now(),db=getDb();db.prepare("INSERT INTO service_connections(service_id,user_created,updated_at) VALUES(?,0,?) ON CONFLICT(service_id) DO NOTHING").run(id,now);db.prepare("UPDATE service_connections SET last_test_at=?,last_success_at=CASE WHEN ? THEN ? ELSE last_success_at END,last_latency_ms=?,last_error=?,updated_at=? WHERE service_id=?").run(now,d.success?1:0,now,d.latencyMs,d.error??null,now,id);}
}
