import test from "node:test";
import assert from "node:assert/strict";
import { createServer } from "node:http";
import { mkdtempSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { closeDb, getDb } from "../persistence/db.js";
import { config } from "../config.js";
import { resolveServiceEndpoint, type ServiceDefinition } from "./serviceRegistry.js";
import { ServiceAdapter } from "./serviceAdapter.js";
import type { TaskRequest } from "./contract.js";
import { WorkspaceStore } from "../workspaces/workspaceStore.js";
import { ArtifactStore } from "../workspaces/artifactStore.js";

const service=(overrides:Partial<ServiceDefinition>={}):ServiceDefinition=>({id:"generic",name:"Generic",enabled:true,transport:"task_http",endpoint:"http://localhost:1",capabilities:["cap"],priority:1,riskByCapability:{cap:"LOW"},auth:{type:"none"},...overrides});
const request:TaskRequest={schema_version:"1.0",task_id:"task",trace_id:"trace",idempotency_key:"key",capability:"cap",objective:"objective",context:{},constraints:[],priority:"medium",permissions:[]};

test("software factory resolves local in-process by default, ENV overrides to HTTP, and generic services are never rewritten",()=>{const old={PORT:process.env.PORT,API_PORT:process.env.API_PORT,URL:process.env.SOFTWARE_FACTORY_URL};try{delete process.env.SOFTWARE_FACTORY_URL;process.env.PORT="12345";process.env.API_PORT="54321";const local=resolveServiceEndpoint(service({id:"software_factory",transport:"local",endpoint:"software_factory"}));assert.equal(local.endpoint,"software_factory");assert.equal(local.transport,"local");assert.equal(local.source,"FACTORY");process.env.SOFTWARE_FACTORY_URL="https://factory.example";const viaEnv=resolveServiceEndpoint(service({id:"software_factory",transport:"local",endpoint:"software_factory"}));assert.equal(viaEnv.endpoint,"https://factory.example");assert.equal(viaEnv.transport,"task_http");assert.equal(viaEnv.source,"ENVIRONMENT");delete process.env.SOFTWARE_FACTORY_URL;const generic=resolveServiceEndpoint(service({endpoint:"http://localhost:4000"}));assert.equal(generic.endpoint,"http://localhost:4000");assert.equal(generic.transport,"task_http");}finally{for(const [key,value] of Object.entries({PORT:old.PORT,API_PORT:old.API_PORT,SOFTWARE_FACTORY_URL:old.URL}))value===undefined?delete process.env[key]:process.env[key]=value;}});

test("task_http isolates bearer credentials and fails before network when missing",async()=>{const received:string[]=[];const server=createServer((req,res)=>{received.push(String(req.headers.authorization));res.writeHead(200,{"content-type":"application/json"});res.end(JSON.stringify({events:[]}));});await new Promise<void>(resolve=>server.listen(0,"127.0.0.1",resolve));const address=server.address();assert.ok(address&&typeof address!=="string");const endpoint=`http://127.0.0.1:${address.port}`,adapter=new ServiceAdapter();const oldApi=process.env.API_TOKEN,oldOwn=process.env.MY_SERVICE_TOKEN;try{process.env.API_TOKEN="jarvis-secret";await adapter.dispatchTask(service({endpoint}),request);assert.equal(received.pop(),"undefined");process.env.MY_SERVICE_TOKEN="connector-secret";await adapter.dispatchTask(service({endpoint,auth:{type:"bearer_env",envVar:"MY_SERVICE_TOKEN"}}),request);assert.equal(received.pop(),"Bearer connector-secret");delete process.env.MY_SERVICE_TOKEN;const before=received.length,result=await adapter.dispatchTask(service({endpoint,auth:{type:"bearer_env",envVar:"MY_SERVICE_TOKEN"}}),request);assert.equal(result.success,false);assert.equal(received.length,before);if(!result.success)assert.match(result.message,/AUTH_ENV_MISSING/);}finally{oldApi===undefined?delete process.env.API_TOKEN:process.env.API_TOKEN=oldApi;oldOwn===undefined?delete process.env.MY_SERVICE_TOKEN:process.env.MY_SERVICE_TOKEN=oldOwn;server.close();}});

test("artifacts with the same name are immutable versioned snapshots",()=>{config.db.path=":memory:";closeDb();getDb();const files=new WorkspaceStore(mkdtempSync(join(tmpdir(),"versions-"))),workspace=files.create({name:"versions",ownerType:"ADHOC",ownerId:"versions"}),artifacts=new ArtifactStore(files);const first=artifacts.createTextArtifact({workspaceId:workspace.id,name:"report.md",content:"A"}),second=artifacts.createTextArtifact({workspaceId:workspace.id,name:"report.md",content:"B"});assert.notEqual(first.relativePath,second.relativePath);assert.notEqual(first.sha256,second.sha256);assert.equal(artifacts.get(first.id)?.contentStatus,"AVAILABLE");assert.equal(artifacts.get(second.id)?.contentStatus,"AVAILABLE");assert.equal(files.readFile(workspace.id,first.relativePath!).toString(),"A");assert.equal(files.readFile(workspace.id,second.relativePath!).toString(),"B");});

import { ServiceRegistry } from "./serviceRegistry.js";
import { ServiceOrchestrator } from "./serviceOrchestrator.js";
import { OperationStore } from "./operationStore.js";
import { BackgroundRunner } from "../autonomy/backgroundRunner.js";
import { Planner } from "../planning/planner.js";
import { PlanRunner } from "../planning/planRunner.js";
import { randomUUID } from "node:crypto";

const completed=(r:TaskRequest,artifacts:unknown[])=>[{schema_version:"1.0",event_id:randomUUID(),task_id:r.task_id,trace_id:r.trace_id,service:"local_test",sequence:1,type:"TASK_COMPLETED" as const,timestamp:Date.now(),payload:{artifacts}}];
function localHarness(handler:(r:TaskRequest)=>Promise<any[]>){config.db.path=":memory:";config.workspace.root=mkdtempSync(join(tmpdir(),"orchestration-ws-"));closeDb();getDb();const registry=new ServiceRegistry("/missing/services.json");registry.register(service({id:"local_test",transport:"local",endpoint:"local_test",capabilities:["cap"],auth:{type:"none"}}));const adapter=new ServiceAdapter();adapter.registerLocal("local_test",{handleTaskRequest:handler});return new ServiceOrchestrator({registry,adapter,store:new OperationStore()});}

test("invalid event cannot produce files or artifact rows",async()=>{const orchestrator=localHarness(async r=>[{...completed(r,[{kind:"TEXT",name:"x",content_base64:"eA=="}])[0],trace_id:"wrong"}]);const workspace=orchestrator.workspaces.create({name:"w",ownerType:"ADHOC",ownerId:"invalid-event"});await orchestrator.dispatchCapability({action:"DISPATCH_CAPABILITY",capability:"cap",objective:"x"},{workspaceId:workspace.id});assert.equal(orchestrator.workspaces.listFiles(workspace.id).length,0);assert.equal(orchestrator.artifacts.listByWorkspace(workspace.id).length,0);});

test("invalid artifact batch fails closed and background runner continues",async()=>{const orchestrator=localHarness(async r=>completed(r,r.objective==="bad"?[{kind:"TEXT",name:"bad",content_base64:"not base64!"}]:[{kind:"TEXT",name:"good",content_base64:"b2s="}]));const workspace=orchestrator.workspaces.create({name:"w",ownerType:"ADHOC",ownerId:"batch"});const bad=await orchestrator.dispatchCapability({action:"DISPATCH_CAPABILITY",capability:"cap",objective:"bad"},{workspaceId:workspace.id,executionMode:"background"});const good=await orchestrator.dispatchCapability({action:"DISPATCH_CAPABILITY",capability:"cap",objective:"good"},{workspaceId:workspace.id,executionMode:"background"});const runner=new BackgroundRunner(orchestrator);await runner.tick();assert.equal(orchestrator.store.getOperation(bad.taskId)?.status,"FAILED");assert.equal(orchestrator.store.getOperation(bad.taskId)?.error,"INVALID_ARTIFACT_DESCRIPTOR");await runner.tick();assert.equal(orchestrator.store.getOperation(good.taskId)?.status,"COMPLETED");assert.equal(orchestrator.artifacts.listByWorkspace(workspace.id).length,1);});

test("plan workspace is stable, authoritative and propagated to every operation",async()=>{const requests:TaskRequest[]=[];const orchestrator=localHarness(async r=>{requests.push(r);return completed(r,[])}),planner=new Planner(),runner=new PlanRunner(orchestrator,planner,undefined,1);const run=planner.createExecutionPlan("mission",[{local_id:"a",title:"a",capability:"cap",objective:"a",context:{workspace:{id:"llm-choice"}},constraints:[],priority:"low",depends_on:[]},{local_id:"b",title:"b",capability:"cap",objective:"b",context:{},constraints:[],priority:"low",depends_on:["a"]}],orchestrator.registry);assert.ok(run.workspaceId);assert.equal(orchestrator.workspaces.list().length,1);await runner.tick();const background=new BackgroundRunner(orchestrator);await background.tick();await runner.tick();await runner.tick();await background.tick();await runner.tick();const operations=orchestrator.store.listOperations();assert.equal(operations.length,2);assert.ok(operations.every(operation=>operation.workspaceId===run.workspaceId));assert.ok(requests.every(request=>(request.context.workspace as {id:string}).id===run.workspaceId));const restarted=new WorkspaceStore(config.workspace.root);assert.equal(restarted.create({name:"mission",ownerType:"PLAN_RUN",ownerId:run.id}).id,run.workspaceId);assert.equal(restarted.list().length,1);});

test("research enforces limits and successive runs create valid artifact versions",async()=>{const calls:Array<{query:string;count:number|undefined}>=[];const provider={name:"bounded",async search(query:string,count?:number){calls.push({query,count});return Array.from({length:12},(_,index)=>({title:`${query}-${index}`,url:`https://example.com/${index}`,snippet:"snippet"}));}};config.db.path=":memory:";config.workspace.root=mkdtempSync(join(tmpdir(),"research-versions-"));closeDb();getDb();const registry=new ServiceRegistry("/missing/services.json");registry.register(service({id:"research_service",transport:"local",endpoint:"research_service",capabilities:["deep_research"],auth:{type:"none"}}));const adapter=new ServiceAdapter();const {ResearchService}=await import("../services/researchService.js");const orchestrator=new ServiceOrchestrator({registry,adapter});adapter.registerLocal("research_service",new ResearchService(provider));const workspace=orchestrator.workspaces.create({name:"research",ownerType:"ADHOC",ownerId:"research"});for(let run=0;run<2;run++)await orchestrator.dispatchCapability({action:"DISPATCH_CAPABILITY",capability:"deep_research",objective:"topic",context:{queries:Array.from({length:10},(_,index)=>`query-${index}`),maxResultsPerQuery:20}},{workspaceId:workspace.id});assert.equal(calls.length,16);assert.ok(calls.every(call=>call.count===10));const artifacts=orchestrator.artifacts.listByWorkspace(workspace.id);assert.equal(artifacts.length,4);assert.equal(new Set(artifacts.map(artifact=>artifact.relativePath)).size,4);assert.ok(artifacts.every(artifact=>artifact.contentStatus==="AVAILABLE"));assert.equal(artifacts.filter(artifact=>artifact.name==="research-sources.json").length,2);assert.equal(artifacts.filter(artifact=>artifact.name==="research-report.md").length,2);});

test("terminal operation rejects a new completion before artifact effects",async()=>{const orchestrator=localHarness(async r=>{const first=completed(r,[{kind:"TEXT",name:"A",content_base64:"QQ=="}])[0];return[first,{...first,event_id:randomUUID(),sequence:2,payload:{artifacts:[{kind:"TEXT",name:"B",content_base64:"Qg=="}]}}]});const workspace=orchestrator.workspaces.create({name:"terminal",ownerType:"ADHOC",ownerId:"terminal"});const result=await orchestrator.dispatchCapability({action:"DISPATCH_CAPABILITY",capability:"cap",objective:"terminal"},{workspaceId:workspace.id});assert.equal(result.status,"COMPLETED");assert.deepEqual(orchestrator.artifacts.listByWorkspace(workspace.id).map(a=>a.name),["A"]);});

test("exact duplicate completion is ignored idempotently",async()=>{const orchestrator=localHarness(async r=>{const event=completed(r,[{kind:"TEXT",name:"once",content_base64:"MQ=="}])[0];return[event,event]});const workspace=orchestrator.workspaces.create({name:"duplicate",ownerType:"ADHOC",ownerId:"duplicate"});const result=await orchestrator.dispatchCapability({action:"DISPATCH_CAPABILITY",capability:"cap",objective:"duplicate"},{workspaceId:workspace.id});assert.equal(result.status,"COMPLETED");assert.equal(orchestrator.artifacts.listByWorkspace(workspace.id).length,1);});

test("invalid trace, service and schema fail closed without retry",async()=>{for(const mutation of [{trace_id:"wrong"},{service:"wrong"},{schema_version:"2.0"}]){const orchestrator=localHarness(async r=>[{...completed(r,[{kind:"TEXT",name:"never",content_base64:"WA=="}])[0],...mutation}]);const workspace=orchestrator.workspaces.create({name:"invalid",ownerType:"ADHOC",ownerId:randomUUID()});const result=await orchestrator.dispatchCapability({action:"DISPATCH_CAPABILITY",capability:"cap",objective:"invalid"},{workspaceId:workspace.id});const operation=orchestrator.store.getOperation(result.taskId);assert.equal(operation?.status,"FAILED");assert.equal(operation?.error,"INVALID_SERVICE_EVENT_STATE_UNKNOWN");assert.equal(operation?.retryable,false);assert.equal(orchestrator.artifacts.listByWorkspace(workspace.id).length,0);}});

test("TASK_PROGRESS remains applicable while RUNNING",()=>{config.db.path=":memory:";closeDb();getDb();const store=new OperationStore();store.createOperation({taskId:"progress",traceId:"trace",idempotencyKey:"progress",objective:"x",capability:"cap",selectedService:"local_test",status:"DISPATCHING"});const event=(sequence:number)=>({schema_version:"1.0",event_id:randomUUID(),task_id:"progress",trace_id:"trace",service:"local_test",sequence,type:"TASK_PROGRESS" as const,timestamp:Date.now(),payload:{message:"working"}});assert.equal(store.processEvent(event(1)).applied,true);assert.equal(store.getOperation("progress")?.status,"RUNNING");assert.equal(store.processEvent(event(2)).applied,true);assert.equal(store.getOperation("progress")?.status,"RUNNING");});
