import {beforeEach,test} from "node:test"; import assert from "node:assert/strict";
import {closeDb,getDb} from "../persistence/db.js"; import {config} from "../config.js"; import {ServiceRegistry} from "../orchestration/serviceRegistry.js"; import {ServiceOrchestrator} from "../orchestration/serviceOrchestrator.js"; import type {ServiceAdapter} from "../orchestration/serviceAdapter.js"; import type {ServiceEvent,TaskRequest} from "../orchestration/contract.js"; import {BackgroundRunner} from "./backgroundRunner.js"; import {NotificationStore} from "./notificationStore.js"; import {TaskStore} from "../tasks/taskStore.js"; import {Scheduler} from "./scheduler.js";
beforeEach(()=>{closeDb();config.db.path=":memory:";getDb();});
function harness(risk="LOW"){const registry=new ServiceRegistry("/none");registry.register({id:"test",name:"test",enabled:true,endpoint:"local",capabilities:["cap"],priority:1,riskByCapability:{cap:risk as any}});let calls=0;const adapter={dispatchTask:async(_e:string,r:TaskRequest)=>{calls++;const ev=(sequence:number,type:ServiceEvent["type"]):ServiceEvent=>({schema_version:"1.0",event_id:`${r.task_id}-${sequence}`,task_id:r.task_id,trace_id:r.trace_id,service:"test",sequence,type,timestamp:Date.now(),payload:type==="TASK_COMPLETED"?{value:1}:{}});return{success:true as const,events:[ev(1,"TASK_ACCEPTED"),ev(2,"TASK_COMPLETED")]};}} as ServiceAdapter;return{orchestrator:new ServiceOrchestrator({registry,adapter}),calls:()=>calls};}
const d={action:"DISPATCH_CAPABILITY" as const,capability:"cap",objective:"mission"};
test("background retourne puis le runner dispatche exactement une fois",async()=>{const h=harness();const op=await h.orchestrator.dispatchCapability(d,{executionMode:"background"});assert.equal(op.status,"QUEUED");assert.equal(h.calls(),0);const runner=new BackgroundRunner(h.orchestrator);await Promise.all([runner.tick(),runner.tick()]);assert.equal(h.calls(),1);assert.equal(h.orchestrator.store.getOperation(op.taskId)?.status,"COMPLETED");});
test("HIGH attend; approbation background met en queue; CRITICAL reste renforcé",async()=>{const h=harness("HIGH");const op=await h.orchestrator.dispatchCapability(d,{executionMode:"background"});assert.equal(op.status,"WAITING_PERMISSION");assert.equal((await h.orchestrator.approvePendingOperation(op.taskId))?.status,"QUEUED");assert.equal(h.calls(),0);const c=harness("CRITICAL");const cop=await c.orchestrator.dispatchCapability(d,{executionMode:"background"});assert.equal(await c.orchestrator.approvePendingOperation(cop.taskId,"no"),null);assert.equal((await c.orchestrator.approvePendingOperation(cop.taskId,"APPROVE_CRITICAL"))?.status,"QUEUED");});
test("cancel avant dispatch est réel mais RUNNING reste non garanti",async()=>{const h=harness();const q=await h.orchestrator.dispatchCapability(d,{executionMode:"background"});assert.equal(h.orchestrator.store.cancel(q.taskId)?.cancelled,true);await new BackgroundRunner(h.orchestrator).tick();assert.equal(h.calls(),0);const high=harness("HIGH");const w=await high.orchestrator.dispatchCapability(d,{executionMode:"background"});assert.equal(high.orchestrator.store.cancel(w.taskId)?.cancelled,true);h.orchestrator.store.createOperation({taskId:"run",traceId:"t",idempotencyKey:"run",objective:"x",capability:"cap",selectedService:"test",status:"RUNNING",executionMode:"background"});const result=h.orchestrator.store.cancel("run")!;assert.equal(result.cancelled,false);assert.equal(result.requested,true);assert.equal(result.operation.status,"RUNNING");});
test("recovery échoue fermé et notifie sans rejeu",()=>{const h=harness();h.orchestrator.store.createOperation({taskId:"crash",traceId:"t",idempotencyKey:"crash",objective:"x",capability:"cap",selectedService:"test",status:"DISPATCHING",executionMode:"background"});assert.equal(new BackgroundRunner(h.orchestrator).recover(),1);assert.equal(h.orchestrator.store.getOperation("crash")?.error,"INTERRUPTED_EXECUTION_STATE_UNKNOWN");assert.equal(new NotificationStore().list()[0].type,"RECOVERY_REQUIRED");assert.equal(h.calls(),0);});
test("scheduler reminder atomique, répétitif, et disabled",async()=>{const h=harness(),tasks=new TaskStore(),notes=new NotificationStore(),scheduler=new Scheduler(h.orchestrator,tasks,notes);const due=100;tasks.createSchedule({title:"r",taskType:"REMINDER",nextRunAt:due});await Promise.all([scheduler.tick(101),scheduler.tick(101)]);assert.equal(notes.list().length,1);const repeating=tasks.createSchedule({title:"repeat",taskType:"REMINDER",nextRunAt:due,repeatIntervalMs:100});await scheduler.tick(101);assert.equal(tasks.get(repeating.id)?.nextRunAt,200);const off=tasks.createSchedule({title:"off",taskType:"REMINDER",nextRunAt:due});tasks.setEnabled(off.id,false);await scheduler.tick(101);assert.equal(notes.list().filter(n=>n.taskId===off.id).length,0);});
test("scheduler dispatch ne crée qu'une opération background",async()=>{const h=harness(),tasks=new TaskStore(),scheduler=new Scheduler(h.orchestrator,tasks);tasks.createSchedule({title:"go",taskType:"DISPATCH",nextRunAt:1,payload:d});await Promise.all([scheduler.tick(2),scheduler.tick(2)]);assert.equal(h.orchestrator.store.listOperations().length,1);assert.equal(h.orchestrator.store.listOperations()[0].executionMode,"background");assert.equal(h.calls(),0);});
test("WATCH baseline, résultat identique, puis changement unique",async()=>{const h=harness(),tasks=new TaskStore(),notes=new NotificationStore(),scheduler=new Scheduler(h.orchestrator,tasks,notes);const watch=tasks.createSchedule({title:"watch",taskType:"WATCH",nextRunAt:1,repeatIntervalMs:10,payload:d});await scheduler.tick(2);await new BackgroundRunner(h.orchestrator,notes).tick();await scheduler.tick(3);assert.ok(tasks.get(watch.id)?.lastResultHash);assert.equal(notes.list().filter(n=>n.type==="WATCH_CHANGED").length,0);const op=h.orchestrator.store.listOperations()[0];getDb().prepare(`UPDATE service_operations SET result=?,watch_processed_at=NULL WHERE task_id=?`).run(JSON.stringify({value:2,timestamp:999}),op.taskId);await scheduler.tick(4);await scheduler.tick(4);assert.equal(notes.list().filter(n=>n.type==="WATCH_CHANGED").length,1);});
test("notification inbox list/count/read",()=>{const n=new NotificationStore();const x=n.create({type:"REMINDER_DUE",severity:"info",title:"a",message:"b"});assert.equal(n.unreadCount(),1);assert.equal(n.list(true).length,1);assert.equal(n.markRead(x.id),true);assert.equal(n.unreadCount(),0);assert.equal(n.markRead("missing"),false);});
test("lignes historiques gardent leurs defaults",()=>{getDb().prepare(`INSERT INTO tasks(id,title,status,due_at,created_at) VALUES('old','old','pending',NULL,1)`).run();getDb().prepare(`INSERT INTO service_operations(task_id,trace_id,idempotency_key,objective,capability,selected_service,status,created_at,updated_at) VALUES('oldop','t','i','o','c','s','QUEUED',1,1)`).run();assert.equal(new TaskStore().get("old")?.taskType,"REMINDER");assert.equal(harness().orchestrator.store.getOperation("oldop")?.executionMode,"foreground");});

test("CANCELLED est terminal pour les replays background et foreground",async()=>{const h=harness();const key="cancelled-key";const first=await h.orchestrator.dispatchCapability(d,{executionMode:"background",idempotencyKey:key});h.orchestrator.store.cancel(first.taskId);assert.equal((await h.orchestrator.dispatchCapability(d,{executionMode:"background",idempotencyKey:key})).status,"CANCELLED");assert.equal((await h.orchestrator.dispatchCapability(d,{executionMode:"foreground",idempotencyKey:key})).status,"CANCELLED");assert.equal(h.orchestrator.store.updateStatus(first.taskId,"DISPATCHING"),false);assert.equal(h.calls(),0);});

test("claim scheduler n'est finalisé qu'après effet et recovery reprend la même occurrence",async()=>{const h=harness(),tasks=new TaskStore(),notes=new NotificationStore();const reminder=tasks.createSchedule({title:"recover",taskType:"REMINDER",nextRunAt:10});const claimed=tasks.claimDue(11)[0];assert.equal(tasks.get(reminder.id)?.status,"pending");assert.equal(tasks.get(reminder.id)?.nextRunAt,10);assert.equal(tasks.claimDue(11).length,0);assert.equal(tasks.recoverClaims(),1);await new Scheduler(h.orchestrator,tasks,notes).tick(11);assert.equal(notes.list().length,1);assert.equal(tasks.get(reminder.id)?.status,"done");});

test("recovery après création dispatch réutilise la même idempotency key",async()=>{const h=harness(),tasks=new TaskStore();const schedule=tasks.createSchedule({title:"recover dispatch",taskType:"DISPATCH",nextRunAt:20,payload:d});tasks.claimDue(21);await h.orchestrator.dispatchCapability(d,{executionMode:"background",scheduleTaskId:schedule.id,idempotencyKey:`schedule:${schedule.id}:20`});tasks.recoverClaims();await new Scheduler(h.orchestrator,tasks).tick(21);assert.equal(h.orchestrator.store.listOperations().length,1);});

test("recovery avant dispatch reprend l'occurrence et libère aussi un recurring",async()=>{const h=harness(),tasks=new TaskStore(),scheduler=new Scheduler(h.orchestrator,tasks);const dispatch=tasks.createSchedule({title:"before dispatch",taskType:"DISPATCH",nextRunAt:30,payload:d});tasks.claimDue(31);tasks.recoverClaims();await scheduler.tick(31);assert.equal(h.orchestrator.store.listOperations().filter(op=>op.scheduleTaskId===dispatch.id).length,1);const recurring=tasks.createSchedule({title:"recurring",taskType:"REMINDER",nextRunAt:40,repeatIntervalMs:10});tasks.claimDue(41);assert.equal(tasks.recoverClaims(),1);await scheduler.tick(41);assert.equal(tasks.get(recurring.id)?.nextRunAt,50);assert.equal(tasks.claimDue(41).length,0);});

test("requête background invalide échoue sans affamer la suivante",async()=>{const h=harness(),notes=new NotificationStore(),runner=new BackgroundRunner(h.orchestrator,notes);h.orchestrator.store.createOperation({taskId:"bad",traceId:"bad-t",idempotencyKey:"bad-i",objective:"bad",capability:"cap",selectedService:"test",status:"QUEUED",executionMode:"background",queuedAt:1});getDb().prepare(`UPDATE service_operations SET dispatch_request_json='{' WHERE task_id='bad'`).run();const good=await h.orchestrator.dispatchCapability(d,{executionMode:"background",idempotencyKey:"good"});await runner.tick();assert.equal(h.orchestrator.store.getOperation("bad")?.error,"INVALID_DISPATCH_REQUEST");assert.equal(notes.list().some(n=>n.type==="BACKGROUND_FAILED"&&n.operationTaskId==="bad"),true);await runner.tick();assert.equal(h.orchestrator.store.getOperation(good.taskId)?.status,"COMPLETED");assert.equal(h.calls(),1);});

test("payload schedule invalide termine l'occurrence avec last_error",async()=>{const h=harness(),tasks=new TaskStore(),scheduler=new Scheduler(h.orchestrator,tasks);const task=tasks.createSchedule({title:"invalid",taskType:"DISPATCH",nextRunAt:1,payload:{action:"DISPATCH_CAPABILITY",capability:4}});await scheduler.tick(2);assert.equal(tasks.get(task.id)?.status,"done");assert.equal(tasks.get(task.id)?.lastError,"INVALID_SCHEDULE_PAYLOAD");assert.equal(h.calls(),0);});
