import { createHash } from "node:crypto";
import type { DispatchCapabilityDecision } from "../orchestration/contract.js";
import type { ServiceOrchestrator } from "../orchestration/serviceOrchestrator.js";
import { TaskStore } from "../tasks/taskStore.js";
import { NotificationStore } from "./notificationStore.js";
import { getDb } from "../persistence/db.js";

function decision(value:unknown):DispatchCapabilityDecision|null {if(!value||typeof value!=="object"||Array.isArray(value))return null;const v=value as any;if(v.action!=="DISPATCH_CAPABILITY"||typeof v.capability!=="string"||!v.capability||typeof v.objective!=="string"||!v.objective)return null;if(v.context!==undefined&&(!v.context||typeof v.context!=="object"||Array.isArray(v.context)))return null;return {action:v.action,capability:v.capability,objective:v.objective,context:v.context??{},constraints:Array.isArray(v.constraints)&&v.constraints.every((x:unknown)=>typeof x==="string")?v.constraints:[],priority:["low","medium","high","urgent"].includes(v.priority)?v.priority:undefined};}
function stable(value:unknown):unknown {if(Array.isArray(value))return value.map(stable);if(value&&typeof value==="object"){const out:Record<string,unknown>={};for(const key of Object.keys(value as any).sort())if(!/(timestamp|created_at|updated_at|event_id|trace_id)$/i.test(key))out[key]=stable((value as any)[key]);return out;}return value;}
export class Scheduler {
 private timer?:NodeJS.Timeout;private running=false;private stopped=true;
 constructor(private orchestrator:ServiceOrchestrator,private tasks=new TaskStore(),private notifications=new NotificationStore(),private intervalMs=1000){}
 async tick(now=Date.now()):Promise<number>{if(this.running)return 0;this.running=true;try{this.collectWatches();const due=this.tasks.claimDue(now);for(const item of due){let error:string|undefined;if(item.task.taskType==="REMINDER")this.notifications.create({type:"REMINDER_DUE",severity:"info",title:item.task.title,message:"Rappel arrivé à échéance.",taskId:item.task.id},`reminder:${item.task.id}:${item.occurrence}`);else{const d=item.payloadValid?decision(item.payload):null;if(d){const workspaceId=item.task.taskType==="WATCH"&&d.capability==="deep_research"?this.orchestrator.workspaces.create({name:item.task.title,ownerType:"ADHOC",ownerId:`watch:${item.task.id}`}).id:undefined;await this.orchestrator.dispatchCapability(d,{executionMode:"background",scheduleTaskId:item.task.id,idempotencyKey:`schedule:${item.task.id}:${item.occurrence}`,workspaceId});}else error="INVALID_SCHEDULE_PAYLOAD";}this.tasks.finalizeOccurrence(item.task.id,item.occurrence,error);}return due.length;}finally{this.running=false;}}
 private collectWatches():void{const db=getDb();const rows=db.prepare(`SELECT task_id FROM service_operations WHERE status='COMPLETED' AND schedule_task_id IS NOT NULL AND watch_processed_at IS NULL ORDER BY finished_at,created_at`).all() as Array<{task_id:string}>;for(const row of rows){const op=this.orchestrator.store.getOperation(row.task_id)!;const task=this.tasks.get(op.scheduleTaskId!);if(task?.taskType==="WATCH"&&op.result){let parsed:unknown=op.result;try{parsed=JSON.parse(op.result);}catch{}const hash=createHash("sha256").update(JSON.stringify(stable(parsed))).digest("hex");const old=this.tasks.setWatchHash(task.id,hash);if(old&&old!==hash)this.notifications.create({type:"WATCH_CHANGED",severity:"info",title:"Changement détecté",message:task.title,taskId:task.id,operationTaskId:op.taskId},`watch:${task.id}:${hash}`);}db.prepare(`UPDATE service_operations SET watch_processed_at=? WHERE task_id=? AND watch_processed_at IS NULL`).run(Date.now(),op.taskId);}}
 start():void{if(!this.stopped)return;this.stopped=false;this.tasks.recoverClaims();const loop=async()=>{if(this.stopped)return;await this.tick();if(!this.stopped)this.timer=setTimeout(loop,this.intervalMs);};this.timer=setTimeout(loop,0);} stop():void{this.stopped=true;if(this.timer)clearTimeout(this.timer);}
}
