import { createHash, randomUUID } from "node:crypto";
import { getDb } from "../persistence/db.js";
import { WorkspaceStore } from "./workspaceStore.js";
export type ArtifactKind="FILE"|"TEXT"|"REPORT"|"DATA"|"LINK";
export interface Artifact {id:string;workspaceId:string;planRunId?:string;operationTaskId?:string;kind:ArtifactKind;name:string;mimeType?:string;relativePath?:string;externalUrl?:string;sizeBytes?:number;sha256?:string;metadata?:Record<string,unknown>;createdAt:number;contentStatus?:"AVAILABLE"|"MISSING_CONTENT"|"CORRUPT"}
const kinds=new Set(["FILE","TEXT","REPORT","DATA","LINK"]);const rec=(v:unknown):v is Record<string,unknown>=>!!v&&typeof v==="object"&&!Array.isArray(v);
export class ArtifactStore {constructor(readonly files=new WorkspaceStore()){}
 private insert(a:Omit<Artifact,"id"|"createdAt">):Artifact{if(!kinds.has(a.kind)||!a.name.trim()||!this.files.get(a.workspaceId)||!rec(a.metadata??{}))throw new Error("INVALID_ARTIFACT");const id=randomUUID(),createdAt=Date.now();getDb().prepare("INSERT INTO artifacts(id,workspace_id,plan_run_id,operation_task_id,kind,name,mime_type,relative_path,external_url,size_bytes,sha256,metadata_json,created_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?)").run(id,a.workspaceId,a.planRunId??null,a.operationTaskId??null,a.kind,a.name.trim(),a.mimeType??null,a.relativePath??null,a.externalUrl??null,a.sizeBytes??null,a.sha256??null,JSON.stringify(a.metadata??{}),createdAt);return{id,createdAt,...a};}
 createFileArtifact(input:{workspaceId:string;planRunId?:string;operationTaskId?:string;kind?:ArtifactKind;name:string;mimeType?:string;relativePath?:string;content:Buffer;metadata?:Record<string,unknown>}):Artifact{const path=input.relativePath??`artifacts/${randomUUID()}-${input.name.replace(/[^a-zA-Z0-9._-]/g,"_")}`;this.files.writeFile(input.workspaceId,path,input.content);return this.insert({...input,kind:input.kind??"FILE",relativePath:path,sizeBytes:input.content.length,sha256:createHash("sha256").update(input.content).digest("hex")});}
 createTextArtifact(input:{workspaceId:string;planRunId?:string;operationTaskId?:string;kind?:ArtifactKind;name:string;mimeType?:string;relativePath?:string;content:string;metadata?:Record<string,unknown>}):Artifact{return this.createFileArtifact({...input,kind:input.kind??"TEXT",mimeType:input.mimeType??"text/plain; charset=utf-8",content:Buffer.from(input.content) });}
 createLinkArtifact(input:{workspaceId:string;planRunId?:string;operationTaskId?:string;name:string;url:string;metadata?:Record<string,unknown>}):Artifact{let url:URL;try{url=new URL(input.url);}catch{throw new Error("INVALID_ARTIFACT_URL");}if(!["http:","https:"].includes(url.protocol))throw new Error("INVALID_ARTIFACT_URL");return this.insert({...input,kind:"LINK",externalUrl:url.href});}
 private map(r:any):Artifact{const a:Artifact={id:r.id,workspaceId:r.workspace_id,planRunId:r.plan_run_id??undefined,operationTaskId:r.operation_task_id??undefined,kind:r.kind,name:r.name,mimeType:r.mime_type??undefined,relativePath:r.relative_path??undefined,externalUrl:r.external_url??undefined,sizeBytes:r.size_bytes??undefined,sha256:r.sha256??undefined,metadata:JSON.parse(r.metadata_json||"{}"),createdAt:r.created_at};if(a.relativePath){if(!this.files.exists(a.workspaceId,a.relativePath))a.contentStatus="MISSING_CONTENT";else if(a.sha256&&createHash("sha256").update(this.files.readFile(a.workspaceId,a.relativePath)).digest("hex")!==a.sha256)a.contentStatus="CORRUPT";else a.contentStatus="AVAILABLE";}return a;}
 get(id:string):Artifact|null{const r=getDb().prepare("SELECT * FROM artifacts WHERE id=?").get(id);return r?this.map(r):null;} listByWorkspace(id:string):Artifact[]{return(getDb().prepare("SELECT * FROM artifacts WHERE workspace_id=? ORDER BY created_at").all(id) as any[]).map(r=>this.map(r));} listByOperation(id:string):Artifact[]{return(getDb().prepare("SELECT * FROM artifacts WHERE operation_task_id=? ORDER BY created_at").all(id) as any[]).map(r=>this.map(r));}
}
