import test from "node:test";
import assert from "node:assert/strict";
import { canonicalSkillCatalog, CANONICAL_SKILL_IDS } from "./catalog.js";
import { SkillRegistry } from "./registry.js";
import { SkillSelector } from "./selector.js";
import { LocalHashingEmbeddingProvider } from "../llm/embeddings.js";

test("catalogue canonique contient exactement 40 identifiants sans collision",()=>{assert.equal(canonicalSkillCatalog.length,40);assert.equal(new Set(CANONICAL_SKILL_IDS).size,40);assert.equal(new Set(canonicalSkillCatalog.map(x=>x.name)).size,40);assert.equal(new Set(canonicalSkillCatalog.flatMap(x=>x.aliases??[])).size,canonicalSkillCatalog.flatMap(x=>x.aliases??[]).length);});
test("selector exclut internal/future et respecte une limite déterministe",async()=>{const registry=new SkillRegistry(new LocalHashingEmbeddingProvider());for(const raw of canonicalSkillCatalog)registry.register({...raw,handler:async()=>"ok"});const selector=new SkillSelector(registry,3);const first=await selector.select("cherche les dernières nouvelles et prix");assert.ok(first.some(x=>x.name==="web_search"));assert.ok(first.some(x=>x.name==="deep_research"));assert.ok(first.length<=3);assert.ok(first.every(x=>x.kind!=="INTERNAL"&&x.kind!=="FUTURE"));assert.deepEqual((await selector.select("texte neutre")).map(x=>x.name),(await selector.select("texte neutre")).map(x=>x.name));});
test("boosts code, rappel et surveillance restent métier",async()=>{const registry=new SkillRegistry(new LocalHashingEmbeddingProvider());for(const raw of canonicalSkillCatalog)registry.register({...raw,handler:async()=>"ok"});const selector=new SkillSelector(registry,8);assert.ok((await selector.select("modifie www/app.js sur GitHub")).some(x=>x.name==="software_development"));assert.ok((await selector.select("programme un rappel")).some(x=>x.name==="schedule_task"));assert.ok((await selector.select("surveille ce changement")).some(x=>x.name==="monitor_condition"));assert.ok(!(await selector.select("ouvre mon calendrier")).some(x=>x.name==="calendar"));});

import { mkdtempSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { config } from "../config.js";
import { closeDb, getDb } from "../persistence/db.js";
import { ServiceRegistry } from "../orchestration/serviceRegistry.js";
import { ServiceOrchestrator } from "../orchestration/serviceOrchestrator.js";
import { ServiceAdapter } from "../orchestration/serviceAdapter.js";
import { ResearchService } from "../services/researchService.js";
import { Planner } from "../planning/planner.js";
import { PlanRunner } from "../planning/planRunner.js";
import { WorkflowRegistry } from "../workflows/workflowRegistry.js";
import { createRuntimeSkills } from "./runtime.js";
import { TaskStore } from "../tasks/taskStore.js";
import { Scheduler } from "../autonomy/scheduler.js";
import { BackgroundRunner } from "../autonomy/backgroundRunner.js";

function harness(){config.db.path=":memory:";config.workspace.root=mkdtempSync(join(tmpdir(),"reusable-"));closeDb();getDb();const services=new ServiceRegistry("/missing.json");services.register({id:"research_service",name:"research",enabled:true,transport:"local",endpoint:"research_service",capabilities:["deep_research"],parallelSafeCapabilities:["deep_research"],priority:10,riskByCapability:{deep_research:"LOW"},auth:{type:"none"}});services.register({id:"software_factory",name:"software",enabled:true,transport:"local",endpoint:"software_factory",capabilities:["software_development"],priority:10,riskByCapability:{software_development:"MEDIUM"},auth:{type:"none"}});services.register({id:"workspace_service",name:"workspace",enabled:true,transport:"local",endpoint:"workspace_service",capabilities:["file_management"],priority:10,riskByCapability:{file_management:"MEDIUM"},auth:{type:"none"}});const adapter=new ServiceAdapter(),orchestrator=new ServiceOrchestrator({registry:services,adapter});adapter.registerLocal("research_service",new ResearchService({name:"test",search:async q=>[{title:q,url:`https://example.test/${encodeURIComponent(q)}`,snippet:"ok"}]}));const planner=new Planner(),runner=new PlanRunner(orchestrator,planner),workflows=new WorkflowRegistry(),skills=createRuntimeSkills(orchestrator,planner,runner,workflows);return{services,orchestrator,planner,runner,workflows,skills,get:(id:string)=>skills.find(s=>s.id===id)!};}

test("file_management transmet le workspace autoritaire et rejette traversal",async()=>{const h=harness(),workspace=h.orchestrator.workspaces.create({name:"files",ownerType:"ADHOC",ownerId:"files"}),skill=h.get("file_management");const result=JSON.parse(await skill.handler!({action:"WRITE",workspaceId:workspace.id,path:"ok.txt",content:"hello"},{} as any));assert.equal(result.status,"COMPLETED");assert.equal(h.orchestrator.store.getOperation(result.taskId)?.workspaceId,workspace.id);assert.equal(h.orchestrator.workspaces.readFile(workspace.id,"ok.txt").toString(),"hello");assert.ok(h.orchestrator.artifacts.listByOperation(result.taskId).every(a=>a.workspaceId===workspace.id));const bad=JSON.parse(await skill.handler!({action:"WRITE",workspaceId:workspace.id,path:"../escape",content:"x"},{} as any));assert.equal(bad.status,"FAILED");});

test("deep_research direct crée un workspace et ses deux artifacts",async()=>{const h=harness(),result=JSON.parse(await h.get("deep_research").handler!({objective:"topic",queries:["a"]},{} as any));assert.equal(result.status,"COMPLETED");assert.ok(result.workspaceId);assert.equal(h.orchestrator.store.getOperation(result.taskId)?.workspaceId,result.workspaceId);assert.deepEqual(result.artifacts.map((a:any)=>a.name).sort(),["research-report.md","research-sources.json"]);});

test("software_development encode TARGET_BRANCH et TARGET_PR dans instructions",async()=>{const h=harness(),calls:any[]=[];(h.orchestrator as any).dispatchCapability=async(d:any)=>{calls.push(d);return{taskId:"x",traceId:"t",status:"COMPLETED",selectedService:"s"};};const skill=h.get("software_development");for(const input of [{targetBranch:"branch"},{targetPr:42},{targetBranch:"branch",targetPr:42},{}])await skill.handler!({objective:"x",filePath:"a.ts",...input},{} as any);assert.match(calls[0].context.instructions,/^TARGET_BRANCH=branch$/);assert.match(calls[1].context.instructions,/^TARGET_PR=42$/);assert.match(calls[2].context.instructions,/TARGET_BRANCH=branch\nTARGET_PR=42/);assert.equal(calls[3].context.instructions,"");assert.equal(calls.every(c=>c.context.neverAutoMerge===true),true);});

test("monitor_web crée une vraie WATCH deep_research",async()=>{const h=harness(),result=JSON.parse(await h.get("execute_workflow").handler!({workflowName:"monitor_web",inputs:{title:"watch",objective:"observe",repeatIntervalMs:60000,firstRunAt:123,queries:["q"]}},{toolCallId:"watch-1"} as any));const task=new TaskStore().get(result.scheduleId)!;assert.equal(task.taskType,"WATCH");assert.equal(task.repeatIntervalMs,60000);const payload=JSON.parse((getDb().prepare("SELECT payload_json FROM tasks WHERE id=?").get(task.id) as any).payload_json);assert.equal(payload.capability,"deep_research");assert.deepEqual(payload.context.queries,["q"]);const scheduler=new Scheduler(h.orchestrator);await scheduler.tick(123);await new BackgroundRunner(h.orchestrator).tick();await scheduler.tick(124);assert.equal(h.orchestrator.store.listOperations()[0].status,"COMPLETED");assert.equal(h.orchestrator.store.listOperations()[0].workspaceId!==undefined,true);});

test("workflow conserve les arrays, valide les types et applique le lifecycle",()=>{const h=harness(),compare=h.workflows.get("compare_sources")!;assert.deepEqual(h.workflows.compile(compare,{topic:"x",queries:["a","b"]}).steps[0].context.queries,["a","b"]);assert.throws(()=>h.workflows.compile(compare,{topic:2}),/WORKFLOW_INPUT_INVALID/);getDb().prepare("UPDATE workflows SET status='DRAFT' WHERE id='compare_sources'").run();assert.throws(()=>h.workflows.execute("compare_sources",{topic:"x"},h.planner,h.services,"draft"),/WORKFLOW_NOT_ACTIVE/);assert.equal(h.workflows.setStatus("compare_sources","ACTIVE",h.services),true);assert.equal(h.workflows.setStatus("compare_sources","DISABLED",h.services),true);assert.throws(()=>h.workflows.execute("compare_sources",{topic:"x"},h.planner,h.services,"disabled"),/WORKFLOW_NOT_ACTIVE/);assert.equal(h.workflows.setStatus("compare_sources","ACTIVE",h.services),true);assert.equal(h.workflows.setStatus("compare_sources","ARCHIVED",h.services),true);assert.throws(()=>h.workflows.setStatus("compare_sources","ACTIVE",h.services),/WORKFLOW_STATUS_TRANSITION_INVALID/);});

test("activation échoue si une capability est indisponible",()=>{const h=harness();getDb().prepare("UPDATE workflows SET status='DRAFT' WHERE id='compare_sources'").run();const empty=new ServiceRegistry("/missing.json");assert.throws(()=>h.workflows.setStatus("compare_sources","ACTIVE",empty),/WORKFLOW_CAPABILITY_UNAVAILABLE/);});

test("execute_workflow déduplique une invocation mais pas deux appels volontaires",async()=>{const h=harness(),skill=h.get("execute_workflow"),input={workflowName:"compare_sources",inputs:{topic:"x",queries:["a"]}};const one=JSON.parse(await skill.handler!(input,{toolCallId:"same"} as any)),replay=JSON.parse(await skill.handler!(input,{toolCallId:"same"} as any)),other=JSON.parse(await skill.handler!(input,{toolCallId:"other"} as any));assert.equal(one.planRunId,replay.planRunId);assert.notEqual(one.planRunId,other.planRunId);assert.equal(h.planner.listRuns().length,2);h.planner.updateRun(one.planRunId,"COMPLETED");h.workflows.reconcileSuccesses();h.workflows.reconcileSuccesses();assert.equal(h.workflows.get("compare_sources")?.successCount,1);});

test("learning ignore les autres missions actives et préférences persistent",()=>{const h=harness(),done=h.planner.createExecutionPlan("done",[{local_id:"a",title:"a",capability:"deep_research",objective:"a",context:{},constraints:[],priority:"low",depends_on:[]}],h.services);for(const n of h.planner.nodes(done.id))h.planner.setStatus(n.id,"done");h.planner.updateRun(done.id,"COMPLETED");h.planner.createExecutionPlan("active",[{local_id:"b",title:"b",capability:"deep_research",objective:"b",context:{},constraints:[],priority:"low",depends_on:[]}],h.services);assert.equal(h.workflows.learnFromPlan(done.id,h.planner).status,"DRAFT");const first=new SkillRegistry(new LocalHashingEmbeddingProvider());first.register({...canonicalSkillCatalog.find(s=>s.id==="web_search")!,handler:async()=>"ok"});first.setEnabled("web_search",false);const restarted=new SkillRegistry(new LocalHashingEmbeddingProvider());restarted.register({...canonicalSkillCatalog.find(s=>s.id==="web_search")!,handler:async()=>"ok"});assert.equal(restarted.isEnabled(restarted.get("web_search")!),false);});

test("monitor_web rejoue le même schedule et refuse sans deep_research",async()=>{const h=harness(),skill=h.get("execute_workflow"),input={workflowName:"monitor_web",inputs:{title:"watch",objective:"observe",repeatIntervalMs:1000,firstRunAt:10}};const first=JSON.parse(await skill.handler!(input,{toolCallId:"monitor-same"} as any)),again=JSON.parse(await skill.handler!(input,{toolCallId:"monitor-same"} as any));assert.equal(first.scheduleId,again.scheduleId);assert.equal(new TaskStore().listSchedules().length,1);const other=JSON.parse(await skill.handler!(input,{toolCallId:"monitor-other"} as any));assert.notEqual(first.scheduleId,other.scheduleId);assert.equal(new TaskStore().listSchedules().length,2);h.services.register({...h.services.getServiceById("research_service")!,enabled:false});const before=new TaskStore().listSchedules().length;await assert.rejects(()=>skill.handler!(input,{toolCallId:"monitor-disabled"} as any),/WORKFLOW_CAPABILITY_UNAVAILABLE/);assert.equal(new TaskStore().listSchedules().length,before);});

test("réservation workflow atomique rollback puis retry sans doublon",()=>{const h=harness(),workflow=h.workflows.get("monitor_web")!,inputs={title:"atomic",objective:"x",repeatIntervalMs:1000,firstRunAt:1},tasks=new TaskStore();assert.throws(()=>h.workflows.executeSchedule(workflow.id,inputs,h.services,"atomic",id=>tasks.get(id),()=>{tasks.createSchedule({title:"orphan",taskType:"WATCH",nextRunAt:1,repeatIntervalMs:1000,payload:{}});throw new Error("CRASH");}),/CRASH/);assert.equal(tasks.listSchedules().length,0);const result=h.workflows.executeSchedule(workflow.id,inputs,h.services,"atomic",id=>tasks.get(id),()=>tasks.createSchedule({title:"kept",taskType:"WATCH",nextRunAt:1,repeatIntervalMs:1000,payload:{}}));assert.equal(tasks.listSchedules().length,1);assert.equal(h.workflows.executeSchedule(workflow.id,inputs,h.services,"atomic",id=>tasks.get(id),()=>{throw new Error("must not create");}).id,result.id);assert.throws(()=>h.workflows.executeSchedule(workflow.id,{...inputs,title:"different"},h.services,"atomic",id=>tasks.get(id),()=>result),/WORKFLOW_INVOCATION_CONFLICT/);});

test("learning sanitize récursivement IDs, secrets, paths, titres et objectifs",()=>{const h=harness(),run=h.planner.createExecutionPlan("learn",[{local_id:"a",title:"task-123 /physical/secret",capability:"deep_research",objective:"trace-456 Authorization bearer abc",context:{taskId:"task-1",nested:{workspace_id:"w",safe:"operation-777"},workspacePath:config.workspace.root,artifact_content:"raw"},constraints:["/etc/passwd","apiKey=value","safe"] ,priority:"low",depends_on:[]}],h.services);for(const n of h.planner.nodes(run.id))h.planner.setStatus(n.id,"done");h.planner.updateRun(run.id,"COMPLETED");const learned=h.workflows.learnFromPlan(run.id,h.planner),serialized=JSON.stringify(learned.steps);for(const forbidden of ["task-123","trace-456","Authorization","bearer abc","taskId","workspace_id","workspacePath","artifact_content","/physical/secret","/etc/passwd","apiKey=value",config.workspace.root])assert.equal(serialized.includes(forbidden),false);assert.equal(serialized.includes("operation-777"),false);});

test("schedule_task et monitor_condition refusent les entrées incomplètes ou temporelles invalides",async()=>{const h=harness(),schedule=h.get("schedule_task"),monitor=h.get("monitor_condition");await assert.rejects(()=>schedule.handler!({action:"CREATE_REMINDER",nextRunAt:1},{} as any),/INVALID_SCHEDULE/);await assert.rejects(()=>schedule.handler!({action:"CREATE_REMINDER",title:"x",nextRunAt:NaN},{} as any),/INVALID_SCHEDULE/);await assert.rejects(()=>schedule.handler!({action:"ENABLE"},{} as any),/INVALID_SCHEDULE/);await assert.rejects(()=>schedule.handler!({action:"CREATE_DISPATCH",title:"x",nextRunAt:1,capability:"deep_research"},{} as any),/INVALID_SCHEDULE/);await assert.rejects(()=>monitor.handler!({title:"x",objective:"x",nextRunAt:1,repeatIntervalMs:0,capability:"deep_research"},{} as any),/INVALID_SCHEDULE/);assert.equal(new TaskStore().listSchedules().length,0);});

test("prompt et ToolDefinitions n'annoncent jamais web_search indisponible",async()=>{const {Agent}=await import("../core/agent.js");const previous=config.webSearch.provider;config.webSearch.provider="none";let prompt="",tools:string[]=[];const llm={name:"capture",supportsNativeTools:true,async complete(messages:any[],options:any){prompt=messages[0].content;tools=(options.tools??[]).map((t:any)=>t.function.name);return{content:"ok"};}};try{const agent=new Agent({llm:llm as any,embeddings:new LocalHashingEmbeddingProvider()});await agent.step("cherche les actualités");assert.equal(tools.includes("web_search"),false);assert.equal(prompt.includes("web_search"),false);assert.equal(tools.includes("execute_mission"),true);assert.equal(tools.includes("dispatch_capability"),false);}finally{config.webSearch.provider=previous;}});
