import type { SkillDefinition, SkillContext } from "../types.js";
import type { ServiceOrchestrator } from "../orchestration/serviceOrchestrator.js";
import type { Planner } from "../planning/planner.js";
import type { PlanRunner } from "../planning/planRunner.js";
import { TaskStore } from "../tasks/taskStore.js";
import { WorkflowRegistry } from "../workflows/workflowRegistry.js";
import { canonicalSkillCatalog } from "./catalog.js";
import { config } from "../config.js";

const schema=(properties:Record<string,unknown>,required:string[]=[]):SkillDefinition["parameters"]=>({type:"object",properties,required,additionalProperties:false});
const object=(v:unknown):Record<string,unknown>=>v&&typeof v==="object"&&!Array.isArray(v)?v as Record<string,unknown>:{};
const strings=(v:unknown):string[]=>Array.isArray(v)&&v.every(x=>typeof x==="string")?v:[];
export function createRuntimeSkills(orchestrator:ServiceOrchestrator,planner:Planner,planRunner:PlanRunner,workflows:WorkflowRegistry):SkillDefinition[]{
 const tasks=new TaskStore(); const base=new Map(canonicalSkillCatalog.map(s=>[s.id!,{...s}]));
 const define=(id:string,parameters:SkillDefinition["parameters"],handler:NonNullable<SkillDefinition["handler"]>)=>Object.assign(base.get(id)!,{parameters,handler});
 const dispatch=(capability:string,input:Record<string,unknown>,context:Record<string,unknown>)=>orchestrator.dispatchCapability({action:"DISPATCH_CAPABILITY",capability,objective:String(input.objective??"").trim(),context,constraints:strings(input.constraints)},{executionMode:input.executionMode==="background"?"background":"foreground"});
 define("software_development",schema({objective:{type:"string"},filePath:{type:"string"},instructions:{type:"string"},exactContent:{type:"string"},targetBranch:{type:"string"},targetPr:{type:"integer"},constraints:{type:"array"},executionMode:{type:"string",enum:["foreground","background"]}},["objective","filePath"]),async i=>JSON.stringify(await dispatch("software_development",i,{filePath:i.filePath,instructions:i.instructions,exactContent:i.exactContent,targetBranch:i.targetBranch,targetPr:i.targetPr,neverAutoMerge:true})));
 define("deep_research",schema({objective:{type:"string"},queries:{type:"array"},maxResultsPerQuery:{type:"integer"},constraints:{type:"array"}},["objective"]),async i=>JSON.stringify(await dispatch("deep_research",i,{queries:i.queries,maxResultsPerQuery:i.maxResultsPerQuery})));
 define("file_management",schema({action:{type:"string",enum:["LIST","READ","WRITE","DELETE"]},workspaceId:{type:"string"},path:{type:"string"},content:{type:"string"},encoding:{type:"string"}},["action","workspaceId"]),async i=>JSON.stringify(await dispatch("file_management",{...i,objective:`${i.action} workspace file`},{workspace:{id:i.workspaceId},action:i.action,path:i.path,...(i.encoding==="base64"?{contentBase64:i.content}:{text:i.content})})));
 define("inspect_task",schema({id:{type:"string"},type:{type:"string",enum:["operation","plan","schedule"]}},["id"]),async i=>{const id=String(i.id),type=i.type;const found=[!type||type==="operation"?orchestrator.store.getOperation(id):null,!type||type==="plan"?planner.getRun(id):null,!type||type==="schedule"?tasks.get(id):null].filter(Boolean);if(found.length>1)return"AMBIGUOUS_TASK_ID";if(!found.length)return"TASK_NOT_FOUND";return JSON.stringify(found[0]);});
 define("cancel_task",schema({id:{type:"string"},type:{type:"string",enum:["operation","plan","schedule"]}},["id"]),async i=>{const id=String(i.id);if(i.type==="plan"||(!i.type&&planner.getRun(id))){const r=planRunner.cancel(id);return r?JSON.stringify({id,status:r.status,result:r.status==="CANCELLED"?"cancelled":"cancellation_requested"}):"TASK_NOT_FOUND";}if(i.type==="schedule"||(!i.type&&tasks.get(id))){return JSON.stringify({id,result:tasks.setEnabled(id,false)?"cancelled":"TASK_NOT_FOUND"});}const r=orchestrator.store.cancel(id);return r?JSON.stringify({id,result:r.cancelled?"cancelled":r.requested?"cancellation_requested":"not_cancelled",status:r.operation.status}):"TASK_NOT_FOUND";});
 const schedule=async(i:Record<string,unknown>,watch=false)=>{const capability=String(i.capability??"");if(!orchestrator.registry.findServiceForCapability(capability))return"UNKNOWN_CAPABILITY";return JSON.stringify(tasks.createSchedule({title:String(i.title),taskType:watch?"WATCH":"DISPATCH",nextRunAt:Number(i.nextRunAt),repeatIntervalMs:i.repeatIntervalMs===undefined?undefined:Number(i.repeatIntervalMs),payload:{action:"DISPATCH_CAPABILITY",capability,objective:String(i.objective),context:object(i.context),constraints:strings(i.constraints)}}));};
 define("schedule_task",schema({action:{type:"string"},id:{type:"string"},title:{type:"string"},nextRunAt:{type:"number"},capability:{type:"string"},objective:{type:"string"},context:{type:"object"},constraints:{type:"array"},repeatIntervalMs:{type:"number"}},["action"]),async i=>{switch(i.action){case"LIST":return JSON.stringify(tasks.listSchedules());case"ENABLE":case"DISABLE":return JSON.stringify({ok:tasks.setEnabled(String(i.id),i.action==="ENABLE")});case"COMPLETE":return JSON.stringify({ok:tasks.complete(String(i.id))});case"CREATE_REMINDER":return JSON.stringify(tasks.createSchedule({title:String(i.title),taskType:"REMINDER",nextRunAt:Number(i.nextRunAt),repeatIntervalMs:i.repeatIntervalMs as number|undefined}));case"CREATE_DISPATCH":return schedule(i);default:return"INVALID_SCHEDULE_ACTION";}});
 define("monitor_condition",schema({title:{type:"string"},objective:{type:"string"},nextRunAt:{type:"number"},repeatIntervalMs:{type:"number"},capability:{type:"string"},context:{type:"object"},constraints:{type:"array"}},["title","objective","nextRunAt","capability"]),async i=>schedule(i,true));
 define("execute_workflow",schema({workflowId:{type:"string"},workflowName:{type:"string"},inputs:{type:"object"}},["inputs"]),async i=>{const run=workflows.execute(String(i.workflowId??i.workflowName??""),object(i.inputs),planner,orchestrator.registry);const w=workflows.get(String(i.workflowId??i.workflowName));return JSON.stringify({workflowId:w!.id,workflowVersion:w!.version,planRunId:run.id,workspaceId:run.workspaceId,status:run.status});});
 define("manage_skill",schema({action:{type:"string"},skillId:{type:"string"},workflowId:{type:"string"},planRunId:{type:"string"}},["action"]),async(i,ctx:SkillContext)=>{const registry=(ctx as any).skillRegistry;switch(i.action){case"LIST":return JSON.stringify(registry.list().map((s:SkillDefinition)=>({id:s.id,enabled:registry.isEnabled(s)})));case"ENABLE":case"DISABLE":registry.setEnabled(String(i.skillId),i.action==="ENABLE");return JSON.stringify({ok:true});case"LIST_WORKFLOWS":return JSON.stringify(workflows.list());case"LEARN_WORKFLOW_FROM_PLAN":return JSON.stringify(workflows.learnFromPlan(String(i.planRunId),planner));case"APPROVE_WORKFLOW":return JSON.stringify({ok:workflows.setStatus(String(i.workflowId),"ACTIVE")});case"DISABLE_WORKFLOW":return JSON.stringify({ok:workflows.setStatus(String(i.workflowId),"DISABLED")});case"ARCHIVE_WORKFLOW":return JSON.stringify({ok:workflows.setStatus(String(i.workflowId),"ARCHIVED")});default:return"INVALID_MANAGE_ACTION";}});
 // A declared AVAILABLE skill is narrowed when its real dependency is absent.
 if(config.webSearch.provider==="none"){const web=base.get("web_search")!;web.availability="UNAVAILABLE";web.unavailableReason="Web provider is not configured";delete web.handler;}
 for(const s of base.values())if(s.serviceCapability&&!orchestrator.registry.findServiceForCapability(s.serviceCapability)){s.availability="UNAVAILABLE";s.unavailableReason=`Service unavailable: ${s.serviceCapability}`;delete s.handler;}
 return [...base.values()];
}
