export type SettingType = "boolean" | "number" | "string" | "enum" | "status" | "action";
export type SettingLevel = "SIMPLE" | "ADVANCED" | "EXPERT";
export type SettingAvailability = "AVAILABLE" | "FUTURE" | "SYSTEM_LOCKED";

export type SettingSection =
  | "general"
  | "intelligence"
  | "autonomy"
  | "connections"
  | "projects_memory"
  | "skills_workflows"
  | "automations"
  | "activity_notifications"
  | "system_maintenance";

export interface SettingValidation {
  min?: number;
  max?: number;
  enumValues?: string[];
  pattern?: string;
}

export interface SettingDefinition {
  key: string;
  section: SettingSection;
  label: string;
  description: string;
  type: SettingType;
  level: SettingLevel;
  defaultValue: unknown;
  editable: boolean;
  availability: SettingAvailability;
  requiresRestart: boolean;
  validation?: SettingValidation;
  unavailableReason?: string;
  plannedChantier?: number;
}

export const SETTINGS_SECTIONS: Array<{ id: SettingSection; label: string; description: string }> = [
  { id: "general", label: "Général", description: "Interface utilisateur, vue de démarrage, thèmes et préférences de navigation" },
  { id: "intelligence", label: "Intelligence", description: "Fournisseurs de modèles LLM, embeddings et hyperparamètres" },
  { id: "autonomy", label: "Autonomie & Sécurité", description: "Gestion du risque, autorisations et limites d'exécution" },
  { id: "connections", label: "Connexions & Services", description: "Orchestration des services distants, endpoints et health checks" },
  { id: "projects_memory", label: "Projets, Fichiers & Mémoire", description: "Workspaces, limites de stockage et persistance mémorielle" },
  { id: "skills_workflows", label: "Skills, Workflows & Agents", description: "Catalogue de compétences, processus métier et spécialistes" },
  { id: "automations", label: "Automatisations", description: "Tâches planifiées, surveillance WATCH et exécution en arrière-plan" },
  { id: "activity_notifications", label: "Activité & Notifications", description: "Logs d'observabilité, métriques et canaux d'alerte" },
  { id: "system_maintenance", label: "Système & Maintenance", description: "État du backend, diagnostics, exports et sauvegardes" },
];

export const SETTINGS_CATALOG: SettingDefinition[] = [
  // --- Général ---
  {
    key: "settings.interfaceMode",
    section: "general",
    label: "Niveau d'affichage de l'interface",
    description: "Définit le niveau de détail des paramètres et de la console Jarvis",
    type: "enum",
    level: "SIMPLE",
    defaultValue: "SIMPLE",
    editable: true,
    availability: "AVAILABLE",
    requiresRestart: false,
    validation: { enumValues: ["SIMPLE", "ADVANCED", "EXPERT"] },
  },
  {
    key: "settings.startupView",
    section: "general",
    label: "Vue de démarrage",
    description: "Écran affiché par défaut au chargement du Command Center",
    type: "enum",
    level: "SIMPLE",
    defaultValue: "CHAT",
    editable: true,
    availability: "AVAILABLE",
    requiresRestart: false,
    validation: { enumValues: ["CHAT", "COMMAND_CENTER", "LAST_VIEW"] },
  },
  {
    key: "settings.timelineMode",
    section: "general",
    label: "Mode de chronologie",
    description: "Format d'affichage des événements de la timeline",
    type: "enum",
    level: "SIMPLE",
    defaultValue: "AUTO",
    editable: true,
    availability: "AVAILABLE",
    requiresRestart: false,
    validation: { enumValues: ["AUTO", "ALWAYS", "COMPACT"] },
  },
  {
    key: "settings.expandCompletedMissions",
    section: "general",
    label: "Déplier les missions terminées",
    description: "Affiche directement les détails des missions terminées dans la timeline",
    type: "boolean",
    level: "SIMPLE",
    defaultValue: false,
    editable: true,
    availability: "AVAILABLE",
    requiresRestart: false,
  },
  {
    key: "settings.theme",
    section: "general",
    label: "Thème visuel",
    description: "Thème graphique de l'interface utilisateur",
    type: "enum",
    level: "SIMPLE",
    defaultValue: "SYSTEM",
    editable: true,
    availability: "AVAILABLE",
    requiresRestart: false,
    validation: { enumValues: ["SYSTEM", "LIGHT", "DARK"] },
  },
  {
    key: "settings.language",
    section: "general",
    label: "Langue de l'interface",
    description: "Langue principale pour la restitution et l'IHM",
    type: "enum",
    level: "SIMPLE",
    defaultValue: "fr",
    editable: false,
    availability: "FUTURE",
    requiresRestart: false,
    validation: { enumValues: ["fr", "en"] },
    unavailableReason: "Multi-langues non raccordé",
    plannedChantier: 8,
  },
  {
    key: "settings.responseLength",
    section: "general",
    label: "Longueur des réponses",
    description: "Niveau de concision des réponses générées",
    type: "enum",
    level: "SIMPLE",
    defaultValue: "NORMAL",
    editable: false,
    availability: "FUTURE",
    requiresRestart: false,
    validation: { enumValues: ["SHORT", "NORMAL", "DETAILED"] },
    unavailableReason: "Longueur de réponse dynamique non raccordée",
    plannedChantier: 8,
  },
  {
    key: "settings.automaticVoiceReading",
    section: "general",
    label: "Lecture vocale automatique",
    description: "Synthèse vocale automatique des réponses de Jarvis",
    type: "boolean",
    level: "SIMPLE",
    defaultValue: false,
    editable: false,
    availability: "FUTURE",
    requiresRestart: false,
    unavailableReason: "Lecture vocale non raccordée",
    plannedChantier: 10,
  },

  // --- Intelligence ---
  {
    key: "intelligence.activeProvider",
    section: "intelligence",
    label: "Fournisseur LLM actif",
    description: "Moteur d'intelligence sélectionné de manière autoritaire via le panneau Modèles IA",
    type: "enum",
    level: "SIMPLE",
    defaultValue: "mock",
    editable: false,
    availability: "SYSTEM_LOCKED",
    requiresRestart: false,
    validation: { enumValues: ["anthropic", "openai", "openrouter", "ollama", "infermatic", "mock"] },
    unavailableReason: "Utiliser le panneau Modèles IA (/api/models/select) pour modifier le fournisseur actif",
  },
  {
    key: "intelligence.activeModel",
    section: "intelligence",
    label: "Modèle LLM actif",
    description: "Identifiant du modèle sélectionné de manière autoritaire via le panneau Modèles IA",
    type: "string",
    level: "SIMPLE",
    defaultValue: "undi95/toppy-m-7b",
    editable: false,
    availability: "SYSTEM_LOCKED",
    requiresRestart: false,
    unavailableReason: "Utiliser le panneau Modèles IA (/api/models/select) pour sélectionner un modèle",
  },
  {
    key: "intelligence.skillSelectorMax",
    section: "intelligence",
    label: "Compétences max injectées",
    description: "Nombre maximal de compétences sélectionnées par prompt",
    type: "number",
    level: "ADVANCED",
    defaultValue: 8,
    editable: true,
    availability: "AVAILABLE",
    requiresRestart: false,
    validation: { min: 3, max: 12 },
  },
  {
    key: "intelligence.temperature",
    section: "intelligence",
    label: "Température LLM",
    description: "Contrôle de la créativité et variabilité des réponses",
    type: "number",
    level: "EXPERT",
    defaultValue: 0.7,
    editable: false,
    availability: "FUTURE",
    requiresRestart: false,
    validation: { min: 0, max: 2 },
    unavailableReason: "Override température non raccordé dans la génération LLM",
    plannedChantier: 8,
  },
  {
    key: "intelligence.topP",
    section: "intelligence",
    label: "Top-P LLM",
    description: "Nucleus sampling pour la génération de texte",
    type: "number",
    level: "EXPERT",
    defaultValue: 1.0,
    editable: false,
    availability: "FUTURE",
    requiresRestart: false,
    validation: { min: 0, max: 1 },
    unavailableReason: "Override Top-P non raccordé",
    plannedChantier: 8,
  },
  {
    key: "intelligence.maxOutputTokens",
    section: "intelligence",
    label: "Tokens de sortie max",
    description: "Limite de tokens générés par appel LLM",
    type: "number",
    level: "EXPERT",
    defaultValue: 4000,
    editable: false,
    availability: "FUTURE",
    requiresRestart: false,
    validation: { min: 256, max: 32000 },
    unavailableReason: "Override token max non raccordé",
    plannedChantier: 8,
  },
  {
    key: "intelligence.contextWindowOverride",
    section: "intelligence",
    label: "Surcharge taille de fenêtre",
    description: "Taille de fenêtre de contexte en tokens pour les modèles sans métadonnées",
    type: "number",
    level: "EXPERT",
    defaultValue: 128000,
    editable: false,
    availability: "FUTURE",
    requiresRestart: false,
    unavailableReason: "Override fenêtre contexte non raccordé",
    plannedChantier: 8,
  },
  {
    key: "intelligence.fallbackModel1",
    section: "intelligence",
    label: "Modèle de secours 1",
    description: "Modèle utilisé en cas de panne ou d'erreur du modèle actif",
    type: "string",
    level: "EXPERT",
    defaultValue: "",
    editable: false,
    availability: "FUTURE",
    requiresRestart: false,
    unavailableReason: "Chaînage de fallback model 1 non raccordé",
    plannedChantier: 8,
  },
  {
    key: "intelligence.fallbackModel2",
    section: "intelligence",
    label: "Modèle de secours 2",
    description: "Second modèle de secours secondaire",
    type: "string",
    level: "EXPERT",
    defaultValue: "",
    editable: false,
    availability: "FUTURE",
    requiresRestart: false,
    unavailableReason: "Chaînage de fallback model 2 non raccordé",
    plannedChantier: 8,
  },
  {
    key: "intelligence.visionModel",
    section: "intelligence",
    label: "Modèle multimodal / vision",
    description: "Modèle spécialisé pour l'analyse d'images et documents",
    type: "string",
    level: "EXPERT",
    defaultValue: "",
    editable: false,
    availability: "FUTURE",
    requiresRestart: false,
    unavailableReason: "Modèle vision non raccordé",
    plannedChantier: 8,
  },
  {
    key: "intelligence.codingModel",
    section: "intelligence",
    label: "Modèle de code dédié",
    description: "Modèle optimisé pour la génération et refactorisation de code",
    type: "string",
    level: "EXPERT",
    defaultValue: "",
    editable: false,
    availability: "FUTURE",
    requiresRestart: false,
    unavailableReason: "Modèle coding dédié non raccordé",
    plannedChantier: 8,
  },
  {
    key: "intelligence.researchModel",
    section: "intelligence",
    label: "Modèle de recherche avancée",
    description: "Modèle optimisé pour la synthèse et le raisonnement profond",
    type: "string",
    level: "EXPERT",
    defaultValue: "",
    editable: false,
    availability: "FUTURE",
    requiresRestart: false,
    unavailableReason: "Modèle recherche dédié non raccordé",
    plannedChantier: 8,
  },
  {
    key: "intelligence.utilityModel",
    section: "intelligence",
    label: "Modèle utilitaire léger",
    description: "Modèle rapide pour le classement, le routage et les résumés",
    type: "string",
    level: "EXPERT",
    defaultValue: "",
    editable: false,
    availability: "FUTURE",
    requiresRestart: false,
    unavailableReason: "Modèle utilitaire dédié non raccordé",
    plannedChantier: 8,
  },
  {
    key: "intelligence.localModelPriority",
    section: "intelligence",
    label: "Priorité modèles locaux",
    description: "Favorise l'exécution locale (Ollama) lorsque disponible",
    type: "boolean",
    level: "EXPERT",
    defaultValue: false,
    editable: false,
    availability: "FUTURE",
    requiresRestart: false,
    unavailableReason: "Priorité modèle local non raccordée",
    plannedChantier: 10,
  },
  {
    key: "intelligence.toolCompatibilityTest",
    section: "intelligence",
    label: "Test compatibilité Tool Calling",
    description: "Vérifie le support natif des fonctions par le modèle sélectionné",
    type: "action",
    level: "EXPERT",
    defaultValue: null,
    editable: false,
    availability: "FUTURE",
    requiresRestart: false,
    unavailableReason: "Test de compatibilité tool calling non raccordé",
    plannedChantier: 8,
  },

  // --- Autonomie & Sécurité ---
  {
    key: "autonomy.globalRiskLevel",
    section: "autonomy",
    label: "Politique globale du risque",
    description: "Niveau maximal de risque autorisé sans approbation explicite",
    type: "enum",
    level: "SIMPLE",
    defaultValue: "LOW",
    editable: false,
    availability: "FUTURE",
    requiresRestart: false,
    validation: { enumValues: ["LOW", "MEDIUM", "HIGH", "CRITICAL"] },
    unavailableReason: "Niveau de risque global non raccordé au runtime",
    plannedChantier: 8,
  },
  {
    key: "autonomy.autoMergePr",
    section: "autonomy",
    label: "Fusion automatique des PRs",
    description: "Autorisation de fusion sans révision humaine (VERROUILLÉ)",
    type: "boolean",
    level: "SIMPLE",
    defaultValue: false,
    editable: false,
    availability: "SYSTEM_LOCKED",
    requiresRestart: false,
    unavailableReason: "INTERDIT PAR LE SYSTÈME",
  },
  {
    key: "autonomy.maxIterations",
    section: "autonomy",
    label: "Tours de boucle agent max",
    description: "Nombre d'itérations maximales par appel avant arrêt de sécurité",
    type: "number",
    level: "ADVANCED",
    defaultValue: 5,
    editable: true,
    availability: "AVAILABLE",
    requiresRestart: false,
    validation: { min: 1, max: 20 },
  },
  {
    key: "autonomy.permissionMatrix",
    section: "autonomy",
    label: "Matrice de permissions granulaires",
    description: "Contrôle d'accès fin par domaine (READ, WRITE, DELETE, EXECUTE...)",
    type: "enum",
    level: "EXPERT",
    defaultValue: "READ",
    editable: false,
    availability: "FUTURE",
    requiresRestart: false,
    validation: { enumValues: ["READ", "WRITE", "DELETE", "EXECUTE", "SEND", "PURCHASE", "COMPUTER_CONTROL"] },
    unavailableReason: "Matrice de permissions granulaires non raccordée",
    plannedChantier: 8,
  },

  // --- Connexions & Services ---
  {
    key: "connections.autoTestOnStartup",
    section: "connections",
    label: "Health check au démarrage",
    description: "Teste automatiquement les connexions distantes au lancement",
    type: "boolean",
    level: "ADVANCED",
    defaultValue: true,
    editable: false,
    availability: "FUTURE",
    requiresRestart: false,
    unavailableReason: "Test automatique au démarrage non raccordé",
    plannedChantier: 8,
  },
  {
    key: "connections.healthTimeoutMs",
    section: "connections",
    label: "Timeout Health Check (ms)",
    description: "Délai d'attente maximum pour les requêtes de santé des services",
    type: "number",
    level: "EXPERT",
    defaultValue: 5000,
    editable: false,
    availability: "FUTURE",
    requiresRestart: false,
    validation: { min: 1000, max: 30000 },
    unavailableReason: "Timeout global de santé non raccordé",
    plannedChantier: 8,
  },
  {
    key: "connections.requestTimeoutMs",
    section: "connections",
    label: "Timeout Tâches HTTP (ms)",
    description: "Délai d'attente maximum pour l'exécution des requêtes de tâches",
    type: "number",
    level: "EXPERT",
    defaultValue: 120000,
    editable: false,
    availability: "FUTURE",
    requiresRestart: false,
    validation: { min: 5000, max: 600000 },
    unavailableReason: "Timeout global de requête non raccordé",
    plannedChantier: 8,
  },

  // --- Projets, Fichiers & Mémoire ---
  {
    key: "projects.workspaceMaxFileBytes",
    section: "projects_memory",
    label: "Taille max par fichier workspace (octets)",
    description: "Limite de poids d'un fichier individuel déposé dans le workspace",
    type: "number",
    level: "ADVANCED",
    defaultValue: 10485760,
    editable: true,
    availability: "AVAILABLE",
    requiresRestart: false,
    validation: { min: 1024, max: 104857600 },
  },
  {
    key: "projects.workspaceMaxTotalBytes",
    section: "projects_memory",
    label: "Stockage total max par workspace (octets)",
    description: "Plafond global de stockage pour l'ensemble des fichiers d'un projet",
    type: "number",
    level: "ADVANCED",
    defaultValue: 52428800,
    editable: true,
    availability: "AVAILABLE",
    requiresRestart: false,
    validation: { min: 1048576, max: 1073741824 },
  },
  {
    key: "projects.projectIsolation",
    section: "projects_memory",
    label: "Isolation stricte des projets",
    description: "Empêche le partage de mémoire et d'artefacts entre projets",
    type: "boolean",
    level: "EXPERT",
    defaultValue: false,
    editable: false,
    availability: "FUTURE",
    requiresRestart: false,
    unavailableReason: "Isolation projet non raccordée",
    plannedChantier: 8,
  },
  {
    key: "projects.knowledgeRag",
    section: "projects_memory",
    label: "Indexation sémantique Vector DB / RAG",
    description: "Moteur de recherche vectoriel avancé sur la base de connaissances",
    type: "boolean",
    level: "EXPERT",
    defaultValue: false,
    editable: false,
    availability: "FUTURE",
    requiresRestart: false,
    unavailableReason: "RAG / Vector DB avancé non raccordé",
    plannedChantier: 8,
  },
  {
    key: "projects.autoIndexing",
    section: "projects_memory",
    label: "Indexation automatique des fichiers",
    description: "Vectorisation à la volée des documents ajoutés au workspace",
    type: "boolean",
    level: "EXPERT",
    defaultValue: false,
    editable: false,
    availability: "FUTURE",
    requiresRestart: false,
    unavailableReason: "Indexation automatique non raccordée",
    plannedChantier: 8,
  },
  {
    key: "projects.memoryRetentionDays",
    section: "projects_memory",
    label: "Rétention de la mémoire de travail (jours)",
    description: "Période avant nettoyage automatique des souvenirs non consolidés",
    type: "number",
    level: "EXPERT",
    defaultValue: 30,
    editable: false,
    availability: "FUTURE",
    requiresRestart: false,
    validation: { min: 1, max: 365 },
    unavailableReason: "Rétention mémoire programmable non raccordée",
    plannedChantier: 8,
  },

  // --- Skills, Workflows & Agents ---
  {
    key: "skills.reflectionEveryNSteps",
    section: "skills_workflows",
    label: "Intervalle de réflexion (tours)",
    description: "Fréquence de déclenchement du moteur de réflexion autonome",
    type: "number",
    level: "ADVANCED",
    defaultValue: 8,
    editable: true,
    availability: "AVAILABLE",
    requiresRestart: false,
    validation: { min: 1, max: 50 },
  },
  {
    key: "skills.studioProduct",
    section: "skills_workflows",
    label: "Product Studio",
    description: "Espace de création et cadrage de fonctionnalités produit",
    type: "boolean",
    level: "EXPERT",
    defaultValue: false,
    editable: false,
    availability: "FUTURE",
    requiresRestart: false,
    unavailableReason: "Product Studio non raccordé",
    plannedChantier: 9,
  },
  {
    key: "skills.studioCreative",
    section: "skills_workflows",
    label: "Creative Studio",
    description: "Génération de visuels, copies et contenus créatifs",
    type: "boolean",
    level: "EXPERT",
    defaultValue: false,
    editable: false,
    availability: "FUTURE",
    requiresRestart: false,
    unavailableReason: "Creative Studio non raccordé",
    plannedChantier: 9,
  },
  {
    key: "skills.officeCommercial",
    section: "skills_workflows",
    label: "Commercial Office",
    description: "Gestion des devis, relances et prospection commerciale",
    type: "boolean",
    level: "EXPERT",
    defaultValue: false,
    editable: false,
    availability: "FUTURE",
    requiresRestart: false,
    unavailableReason: "Commercial Office non raccordé",
    plannedChantier: 9,
  },
  {
    key: "skills.officeMarketing",
    section: "skills_workflows",
    label: "Marketing Office",
    description: "Campagnes, SEO, analytics et diffusion multi-canaux",
    type: "boolean",
    level: "EXPERT",
    defaultValue: false,
    editable: false,
    availability: "FUTURE",
    requiresRestart: false,
    unavailableReason: "Marketing Office non raccordé",
    plannedChantier: 9,
  },

  // --- Automatisations ---
  {
    key: "automations.backgroundMaxConcurrent",
    section: "automations",
    label: "Tâches de fond concurrentes max",
    description: "Plafond d'exécution simultanée des processus d'arrière-plan",
    type: "number",
    level: "ADVANCED",
    defaultValue: 3,
    editable: true,
    availability: "AVAILABLE",
    requiresRestart: false,
    validation: { min: 1, max: 8 },
  },
  {
    key: "automations.emailTriggers",
    section: "automations",
    label: "Déclencheurs d'e-mails entrants",
    description: "Exécution automatique de workflows lors de la réception d'e-mails",
    type: "boolean",
    level: "EXPERT",
    defaultValue: false,
    editable: false,
    availability: "FUTURE",
    requiresRestart: false,
    unavailableReason: "Triggers Email non raccordés",
    plannedChantier: 9,
  },
  {
    key: "automations.crmTriggers",
    section: "automations",
    label: "Déclencheurs événements CRM",
    description: "Reactions aux opportunités et mises à jour de fiches clients",
    type: "boolean",
    level: "EXPERT",
    defaultValue: false,
    editable: false,
    availability: "FUTURE",
    requiresRestart: false,
    unavailableReason: "Triggers CRM non raccordés",
    plannedChantier: 9,
  },
  {
    key: "automations.externalEventTriggers",
    section: "automations",
    label: "Webhooks et événements externes",
    description: "Lancement de missions via API webhooks externes",
    type: "boolean",
    level: "EXPERT",
    defaultValue: false,
    editable: false,
    availability: "FUTURE",
    requiresRestart: false,
    unavailableReason: "Triggers d'événements externes non raccordés",
    plannedChantier: 9,
  },

  // --- Activité & Notifications ---
  {
    key: "activity.logLevel",
    section: "activity_notifications",
    label: "Niveau de journalisation",
    description: "Granularité du journal d'activité d'exécution",
    type: "enum",
    level: "ADVANCED",
    defaultValue: "NORMAL",
    editable: false,
    availability: "FUTURE",
    requiresRestart: false,
    validation: { enumValues: ["NORMAL", "DETAILED", "DEBUG"] },
    unavailableReason: "Niveau de journalisation d'activité non raccordé",
    plannedChantier: 8,
  },
  {
    key: "activity.androidPush",
    section: "activity_notifications",
    label: "Notifications Push Android",
    description: "Envoi de notifications vers l'application mobile native",
    type: "boolean",
    level: "EXPERT",
    defaultValue: false,
    editable: false,
    availability: "FUTURE",
    requiresRestart: false,
    unavailableReason: "Push Android non raccordé",
    plannedChantier: 10,
  },
  {
    key: "activity.emailAlerts",
    section: "activity_notifications",
    label: "Alertes e-mail prioritaires",
    description: "Envoi d'e-mails pour les événements à haut risque ou erreurs",
    type: "boolean",
    level: "EXPERT",
    defaultValue: false,
    editable: false,
    availability: "FUTURE",
    requiresRestart: false,
    unavailableReason: "Alerte Email non raccordée",
    plannedChantier: 9,
  },
  {
    key: "activity.smsAlerts",
    section: "activity_notifications",
    label: "Alertes SMS d'urgence",
    description: "Notifications SMS en cas d'intervention requise",
    type: "boolean",
    level: "EXPERT",
    defaultValue: false,
    editable: false,
    availability: "FUTURE",
    requiresRestart: false,
    unavailableReason: "Alerte SMS non raccordée",
    plannedChantier: 10,
  },
  {
    key: "activity.voiceAlerts",
    section: "activity_notifications",
    label: "Annonces vocales d'urgence",
    description: "Alerte sonore synthétisée sur l'appareil mobile",
    type: "boolean",
    level: "EXPERT",
    defaultValue: false,
    editable: false,
    availability: "FUTURE",
    requiresRestart: false,
    unavailableReason: "Alerte vocale non raccordée",
    plannedChantier: 10,
  },

  // --- Système & Maintenance ---
  {
    key: "system.tokenBudget",
    section: "system_maintenance",
    label: "Budget de tokens par prompt",
    description: "Plafond du contexte transmis aux appels LLM (brique budget)",
    type: "number",
    level: "ADVANCED",
    defaultValue: 4000,
    editable: true,
    availability: "AVAILABLE",
    requiresRestart: false,
    validation: { min: 1000, max: 128000 },
  },
  {
    key: "system.apiPort",
    section: "system_maintenance",
    label: "Port du serveur API HTTP",
    description: "Port réseau d'écoute du serveur Node.js (VERROUILLÉ)",
    type: "number",
    level: "EXPERT",
    defaultValue: 3000,
    editable: false,
    availability: "SYSTEM_LOCKED",
    requiresRestart: true,
    unavailableReason: "Port imposé par la variable d'environnement ou la configuration de déploiement",
  },
];
