import test from "node:test";
import assert from "node:assert/strict";
import { closeDb, getDb } from "../persistence/db.js";
import { config } from "../config.js";
import { Planner, validatePlanSteps, type PlanStepSpec } from "./planner.js";
import { PlanRunner } from "./planRunner.js";
import { ServiceRegistry } from "../orchestration/serviceRegistry.js";
import { ServiceOrchestrator } from "../orchestration/serviceOrchestrator.js";
import { BackgroundRunner } from "../autonomy/backgroundRunner.js";
import type { ServiceAdapter } from "../orchestration/serviceAdapter.js";
import { CONTRACT_SCHEMA_VERSION, type ServiceEvent, type TaskRequest } from "../orchestration/contract.js";
import type { ReplanningEngine, ReplanningFacts } from "./replanningEngine.js";

const step=(id:string,deps:string[]=[],capability="cap"):PlanStepSpec=>({local_id:id,title:id,capability,objective:`do ${id}`,context:{},constraints:[],priority:"medium",depends_on:deps});
let sequence=0;
function event(request:TaskRequest,type:ServiceEvent["type"],payload:Record<string,unknown>):ServiceEvent{return{schema_version:CONTRACT_SCHEMA_VERSION,event_id:`event-${++sequence}`,task_id:request.task_id,trace_id:request.trace_id,service:"svc",sequence:1,type,timestamp:Date.now(),payload};}
function setup(options:{risk?:"LOW"|"HIGH";dispatch?:(request:TaskRequest)=>ServiceEvent}={}){
  closeDb();config.db.path=":memory:";const registry=new ServiceRegistry("/missing");registry.register({id:"svc",name:"svc",enabled:true,endpoint:"local",capabilities:["cap"],priority:1,riskByCapability:{cap:options.risk??"LOW"}});let calls=0;
  const adapter={dispatchTask:async(_endpoint:string,request:TaskRequest)=>{calls++;return{success:true as const,events:[options.dispatch?.(request)??event(request,"TASK_COMPLETED",{value:request.objective})]};}} as ServiceAdapter;
  const orchestrator=new ServiceOrchestrator({registry,adapter});return{registry,orchestrator,planner:new Planner(),calls:()=>calls};
}
async function drain(runner:PlanRunner,background:BackgroundRunner,ticks=12){for(let i=0;i<ticks;i++){await runner.tick();await background.tick();}}

test("plan strict: valide, capability/dépendance/cycle rejetés",()=>{const h=setup();assert.equal(validatePlanSteps([step("a"),step("b",["a"])],h.registry).length,2);assert.throws(()=>validatePlanSteps([step("a",[],"unknown")],h.registry),/unknown capability/);assert.throws(()=>validatePlanSteps([step("a",["x"])],h.registry),/unknown dependency/);assert.throws(()=>validatePlanSteps([step("a",["b"]),step("b",["a"])],h.registry),/cycle/);});

test("données JSON persistées corrompues bloquent sans aucune opération",async()=>{for(const [column,value] of [["dependencies_json","{"],["constraints_json","{"],["context_json","["]] as const){const h=setup(),run=h.planner.createExecutionPlan("mission",[step("a")],h.registry);getDb().prepare(`UPDATE plan_nodes SET ${column}=? WHERE plan_run_id=?`).run(value,run.id);await new PlanRunner(h.orchestrator,h.planner).tick();assert.equal(h.orchestrator.store.listOperations().length,0,column);assert.equal(h.planner.getRun(run.id)?.status,"BLOCKED");assert.equal(h.planner.getRun(run.id)?.lastError,"INVALID_PERSISTED_PLAN_NODE");}});

test("priority ou capability persistée invalide bloque sans dispatch",async()=>{for(const [column,value] of [["priority","bogus"],["capability","unknown"]] as const){const h=setup(),run=h.planner.createExecutionPlan("mission",[step("a")],h.registry);getDb().prepare(`UPDATE plan_nodes SET ${column}=? WHERE plan_run_id=?`).run(value,run.id);await new PlanRunner(h.orchestrator,h.planner).tick();assert.equal(h.orchestrator.store.listOperations().length,0);assert.equal(h.planner.getRun(run.id)?.status,"BLOCKED");assert.equal(h.planner.getRun(run.id)?.lastError,"INVALID_PERSISTED_PLAN_NODE");}});

test("ordre déterministe, une étape active, idempotence double tick et achèvement",async()=>{const h=setup(),run=h.planner.createExecutionPlan("mission",[step("a"),step("b")],h.registry),runner=new PlanRunner(h.orchestrator,h.planner),background=new BackgroundRunner(h.orchestrator);await Promise.all([runner.tick(),runner.tick()]);assert.equal(h.orchestrator.store.listOperations().length,1);assert.equal(h.planner.nodes(run.id).filter(node=>node.status==="in_progress").length,1);await drain(runner,background);assert.equal(h.planner.getRun(run.id)?.status,"COMPLETED");assert.equal(h.calls(),2);});

test("replan conserve la branche indépendante et remplace seulement les descendants",async()=>{const dispatched:string[]=[];const h=setup({dispatch:request=>{dispatched.push(request.objective);return request.objective==="do A"?event(request,"TASK_FAILED",{error:"A failed",replannable:true,side_effect_state:"none"}):event(request,"TASK_COMPLETED",{ok:true});}});const run=h.planner.createExecutionPlan("mission",[step("D"),step("A"),step("B"),step("C",["A"])],h.registry);const before=h.planner.nodes(run.id),bId=before.find(node=>node.title==="B")!.id,dId=before.find(node=>node.title==="D")!.id;const replanning={propose:async()=>[step("A2"),step("C2",["A2"])]} as unknown as ReplanningEngine;const runner=new PlanRunner(h.orchestrator,h.planner,replanning),background=new BackgroundRunner(h.orchestrator);await drain(runner,background,20);const nodes=h.planner.nodes(run.id);assert.equal(h.planner.getRun(run.id)?.status,"COMPLETED");assert.equal(nodes.find(node=>node.title==="D")?.id,dId);assert.equal(nodes.find(node=>node.title==="D")?.status,"done");assert.equal(nodes.find(node=>node.title==="B")?.id,bId);assert.equal(nodes.find(node=>node.title==="B")?.status,"done");assert.equal(nodes.find(node=>node.title==="A")?.status,"failed");assert.equal(nodes.find(node=>node.title==="C")?.status,"abandoned");assert.ok(nodes.filter(node=>node.generation===2).every(node=>node.status==="done"));assert.equal(dispatched.filter(value=>value==="do B").length,1);assert.equal(h.planner.getRun(run.id)?.replanCount,1);});

test("replan dupliquant une étape préservée échoue sans créer de second effet",async()=>{const dispatched:string[]=[];const h=setup({dispatch:request=>{dispatched.push(request.objective);return request.objective==="do A"?event(request,"TASK_FAILED",{error:"safe",replannable:true,side_effect_state:"none"}):event(request,"TASK_COMPLETED",{});}});const run=h.planner.createExecutionPlan("mission",[step("A"),step("B")],h.registry);const bId=h.planner.nodes(run.id).find(node=>node.title==="B")!.id;const replanning={propose:async()=>[step("A2"),step("B")]} as unknown as ReplanningEngine;const runner=new PlanRunner(h.orchestrator,h.planner,replanning),background=new BackgroundRunner(h.orchestrator);await drain(runner,background,6);const nodes=h.planner.nodes(run.id);assert.equal(h.planner.getRun(run.id)?.status,"FAILED");assert.equal(h.planner.getRun(run.id)?.lastError,"REPLAN_DUPLICATES_PRESERVED_STEP");assert.equal(nodes.filter(node=>node.title==="B").length,1);assert.equal(nodes.find(node=>node.title==="B")?.id,bId);assert.equal(nodes.filter(node=>node.generation===2).length,0);assert.equal(dispatched.filter(objective=>objective==="do B").length,0);});

test("replan conserve les dépendances externes vers une branche pending",async()=>{const dispatched:string[]=[];const h=setup({dispatch:request=>{dispatched.push(request.objective);return request.objective==="do A"?event(request,"TASK_FAILED",{error:"safe",replannable:true,side_effect_state:"none"}):event(request,"TASK_COMPLETED",{});}});const run=h.planner.createExecutionPlan("mission",[step("A"),step("B"),step("C",["A","B"])],h.registry);const original=h.planner.nodes(run.id),bId=original.find(node=>node.title==="B")!.id;let facts:ReplanningFacts|undefined;const replanning={propose:async(input:ReplanningFacts)=>{facts=input;return[step("A2"),step("C2",["A2"])];}} as unknown as ReplanningEngine;const runner=new PlanRunner(h.orchestrator,h.planner,replanning),background=new BackgroundRunner(h.orchestrator);await drain(runner,background,20);const nodes=h.planner.nodes(run.id),replacementRoot=nodes.find(node=>node.title==="A2")!;assert.deepEqual(facts?.affected.map(node=>node.title),["A","C"]);assert.deepEqual(facts?.preservedPending.map(node=>node.title),["B"]);assert.equal(nodes.find(node=>node.title==="B")?.id,bId);assert.ok(replacementRoot.dependencies.includes(bId));assert.equal(dispatched.filter(objective=>objective==="do B").length,1);assert.ok(dispatched.indexOf("do B")<dispatched.indexOf("do C2"));assert.equal(h.planner.getRun(run.id)?.status,"COMPLETED");});

test("max replans et proposition invalide échouent fermés",async()=>{for(const mode of ["max","invalid"]){const h=setup({dispatch:request=>event(request,"TASK_FAILED",{error:"safe",replannable:true,side_effect_state:"none"})}),run=h.planner.createExecutionPlan("mission",[step("A")],h.registry,mode==="max"?0:2);const replanning={propose:async()=>{throw new Error("INVALID_REPLAN_PROPOSAL");}} as unknown as ReplanningEngine;const runner=new PlanRunner(h.orchestrator,h.planner,replanning),background=new BackgroundRunner(h.orchestrator);await drain(runner,background,4);assert.equal(h.planner.getRun(run.id)?.status,"FAILED");assert.equal(h.planner.getRun(run.id)?.replanCount,0);}});

test("état externe incertain, rejet et annulation ne replanifient jamais",async()=>{for(const terminal of ["TRANSPORT_UNKNOWN","INTERRUPTED_EXECUTION_STATE_UNKNOWN","REJECTED","CANCELLED"]){const h=setup(),run=h.planner.createExecutionPlan("mission",[step("A")],h.registry),runner=new PlanRunner(h.orchestrator,h.planner,{propose:async()=>{throw new Error("must not run");}} as unknown as ReplanningEngine);await runner.tick();const op=h.orchestrator.store.listOperations()[0];if(terminal==="REJECTED")getDb().prepare(`UPDATE service_operations SET status='REJECTED',error='refused' WHERE task_id=?`).run(op.taskId);else if(terminal==="CANCELLED")h.orchestrator.store.cancel(op.taskId);else getDb().prepare(`UPDATE service_operations SET status='FAILED',error=? WHERE task_id=?`).run(terminal,op.taskId);await runner.tick();assert.equal(h.planner.getRun(run.id)?.status,"BLOCKED");assert.equal(h.planner.getRun(run.id)?.replanCount,0);}});

test("recovery relie l'opération existante sans doublon",async()=>{const h=setup(),run=h.planner.createExecutionPlan("mission",[step("a")],h.registry),runner=new PlanRunner(h.orchestrator,h.planner);const node=h.planner.nodes(run.id)[0],key=`plan:${run.id}:node:${node.id}:attempt:1`;getDb().prepare(`UPDATE plan_nodes SET status='in_progress',operation_idempotency_key=? WHERE id=?`).run(key,node.id);const operation=await h.orchestrator.dispatchCapability({action:"DISPATCH_CAPABILITY",capability:"cap",objective:"do a"},{executionMode:"background",idempotencyKey:key});runner.recover();await Promise.all([runner.tick(),runner.tick()]);assert.equal(h.planner.nodes(run.id)[0].operationTaskId,operation.taskId);assert.equal(h.orchestrator.store.listOperations().length,1);});

test("HIGH attend et le refus bloque sans replan",async()=>{const h=setup({risk:"HIGH"}),run=h.planner.createExecutionPlan("mission",[step("a")],h.registry),runner=new PlanRunner(h.orchestrator,h.planner);await runner.tick();const operation=h.orchestrator.store.listOperations()[0];assert.equal(operation.status,"WAITING_PERMISSION");h.orchestrator.store.rejectPendingApproval(operation.taskId);await runner.tick();assert.equal(h.planner.getRun(run.id)?.status,"BLOCKED");assert.equal(h.planner.getRun(run.id)?.replanCount,0);});

test("restore legacy préserve les plans actifs",()=>{const h=setup(),legacy=h.planner.createNode("legacy"),run=h.planner.createExecutionPlan("mission",[step("a")],h.registry);h.planner.restore([legacy]);assert.ok(h.planner.getRun(run.id));assert.equal(h.planner.nodes(run.id).length,1);assert.ok(h.planner.all().some(node=>node.id===run.rootNodeId));});

test("checkpoint duplicate ou message invalide ne produit aucune mutation partielle",async()=>{
  const {Agent}=await import("../core/agent.js");const {MockProvider}=await import("../llm/providers/mock.js");const {LocalHashingEmbeddingProvider}=await import("../llm/embeddings.js");
  closeDb();config.db.path=":memory:";const agent=new Agent({llm:new MockProvider(),embeddings:new LocalHashingEmbeddingProvider()});agent.memory.working.add({role:"user",content:"avant"});const legacy=agent.planner.createNode("legacy");const run=agent.planner.createExecutionPlan("execution",[step("A",[],"software_development")],agent.serviceOrchestrator.registry);const beforeMemory=agent.memory.working.all(),beforeLegacy=agent.planner.legacyNodes();
  const corruptStates=[{workingMemory:[{role:"invalid",content:"x"}],planNodes:[legacy],stepCount:0},{workingMemory:[{role:"user",content:"x"}],planNodes:[legacy,legacy],stepCount:0}];
  for(const [index,state] of corruptStates.entries()){getDb().prepare(`INSERT INTO checkpoints(id,label,created_at,state,kind,schema_version)VALUES(?,?,?,?,?,1)`).run(`corrupt-${index}`,"bad",Date.now(),JSON.stringify(state),"AGENT_STATE");assert.equal(agent.restoreCheckpoint(`corrupt-${index}`),false);assert.deepEqual(agent.memory.working.all(),beforeMemory);assert.deepEqual(agent.planner.legacyNodes(),beforeLegacy);assert.equal(agent.planner.nodes(run.id).length,1);}
});
