import { randomUUID } from "node:crypto";
import { getDb } from "../persistence/db.js";
import type { ServiceOrchestrator } from "../orchestration/serviceOrchestrator.js";
import { savePlanCheckpoint } from "../persistence/checkpoint.js";
import { Planner, type ExecutionPlanNode, type PlanRun } from "./planner.js";
import type { ReplanningEngine } from "./replanningEngine.js";

const LIVE=new Set(["QUEUED","DISPATCHING","RUNNING"]);
export class PlanRunner {
 private timer?:NodeJS.Timeout; private ticking=false;
 constructor(readonly orchestrator:ServiceOrchestrator,readonly planner=new Planner(),private replanning?:ReplanningEngine,private intervalMs=500){}
 start(){this.recover();this.timer=setInterval(()=>void this.tick(),this.intervalMs);this.timer.unref?.();}
 stop(){if(this.timer)clearInterval(this.timer);}
 recover(){getDb().prepare(`UPDATE plan_nodes SET claimed_at=NULL WHERE plan_run_id IS NOT NULL AND status='in_progress' AND operation_task_id IS NULL`).run();}
 async tick(){if(this.ticking)return;this.ticking=true;try{for(const run of this.planner.activeRuns())await this.reconcile(run);}finally{this.ticking=false;}}
 private async reconcile(run:PlanRun){let nodes=this.planner.nodes(run.id);const active=nodes.filter(n=>n.status==="in_progress"||n.status==="waiting");
  if(active.length){await this.observe(run,active[0]);return;}
  const current=nodes.filter(n=>n.generation===run.generation&&n.status!=="abandoned"&&n.status!=="cancelled");
  if(current.length>0&&current.every(n=>n.status==="done")){this.planner.updateRun(run.id,"COMPLETED");this.planner.setStatus(run.rootNodeId,"done");return;}
  if(current.some(n=>n.status==="failed")){if(run.status!=="FAILED"&&run.status!=="BLOCKED")this.planner.updateRun(run.id,"FAILED");return;}
  const done=new Set(nodes.filter(n=>n.status==="done").map(n=>n.id));const ready=current.filter(n=>n.status==="pending"&&n.dependencies.every(d=>done.has(d))).sort((a,b)=>(a.position??0)-(b.position??0))[0];
  if(!ready){this.planner.updateRun(run.id,"BLOCKED","NO_EXECUTABLE_STEP");return;} await this.dispatch(run,ready);
 }
 private async dispatch(run:PlanRun,node:ExecutionPlanNode){const db=getDb(),key=node.operationIdempotencyKey??`plan:${run.id}:node:${node.id}:attempt:${node.attempt}`;const now=Date.now();const claimed=db.prepare(`UPDATE plan_nodes SET status='in_progress',claimed_at=?,operation_idempotency_key=?,updated_at=? WHERE id=? AND status='pending' AND operation_task_id IS NULL`).run(now,key,now,node.id).changes;if(!claimed)return;
  let op=this.orchestrator.store.getByIdempotencyKey(key);if(!op){const result=await this.orchestrator.dispatchCapability({action:"DISPATCH_CAPABILITY",capability:node.capability!,objective:node.objective!,context:node.context,constraints:node.constraints,priority:node.priority},{executionMode:"background",idempotencyKey:key,traceId:`plan-${run.id}`});op=this.orchestrator.store.getOperation(result.taskId);}
  if(!op){this.failNode(run,node,"OPERATION_NOT_PERSISTED",false);return;}db.prepare(`UPDATE plan_nodes SET operation_task_id=?,updated_at=? WHERE id=?`).run(op.taskId,Date.now(),node.id);this.planner.updateRun(run.id,op.status==="WAITING_PERMISSION"?"WAITING_PERMISSION":"RUNNING");await this.observe(run,{...node,status:"in_progress",operationTaskId:op.taskId,operationIdempotencyKey:key});
 }
 private async observe(run:PlanRun,node:ExecutionPlanNode){let op=node.operationTaskId?this.orchestrator.store.getOperation(node.operationTaskId):null;if(!op&&node.operationIdempotencyKey){op=this.orchestrator.store.getByIdempotencyKey(node.operationIdempotencyKey);if(op)getDb().prepare(`UPDATE plan_nodes SET operation_task_id=?,updated_at=? WHERE id=?`).run(op.taskId,Date.now(),node.id);}if(!op){this.planner.setStatus(node.id,"pending");return;}
  if(LIVE.has(op.status)){this.planner.updateRun(run.id,"RUNNING");return;}if(op.status==="WAITING_PERMISSION"){this.planner.setStatus(node.id,"waiting");this.planner.updateRun(run.id,"WAITING_PERMISSION");return;}if(op.status==="WAITING_INPUT"){this.planner.setStatus(node.id,"waiting");this.planner.updateRun(run.id,"BLOCKED","WAITING_INPUT");return;}if(op.status==="COMPLETED"){getDb().prepare(`UPDATE plan_nodes SET status='done',result=?,claimed_at=NULL,updated_at=? WHERE id=?`).run(op.result??null,Date.now(),node.id);this.planner.updateRun(run.id,"RUNNING");return;}if(op.status==="REJECTED"||op.status==="CANCELLED"){this.failNode(run,node,op.error??op.status,false,"BLOCKED");return;}
  if(op.status==="FAILED"){const unknown=(op.error??"").includes("TRANSPORT_UNKNOWN")||(op.error??"").includes("INTERRUPTED_EXECUTION_STATE_UNKNOWN");const event=this.orchestrator.store.listEvents(op.taskId).filter(e=>e.type==="TASK_FAILED").at(-1);const safe=!unknown&&event?.payload.replannable===true&&event.payload.side_effect_state==="none";if(!safe){this.failNode(run,node,op.error??"UNSAFE_FAILURE",false,unknown?"BLOCKED":"FAILED");return;}await this.replan(run,node,op.error??JSON.stringify(event.payload));}
 }
 private failNode(run:PlanRun,node:ExecutionPlanNode,error:string,_replan:boolean,status:"FAILED"|"BLOCKED"="FAILED"){getDb().prepare(`UPDATE plan_nodes SET status='failed',error=?,claimed_at=NULL,updated_at=? WHERE id=?`).run(error,Date.now(),node.id);this.planner.updateRun(run.id,status,error);}
 private async replan(run:PlanRun,node:ExecutionPlanNode,error:string){if(!this.replanning||run.replanCount>=run.maxReplans){this.failNode(run,node,error,false,"FAILED");return;}savePlanCheckpoint(run.id,this.planner);let specs;try{specs=await this.replanning.propose({plan:run,completed:this.planner.nodes(run.id).filter(n=>n.status==="done"),failed:{...node,error},remaining:this.planner.nodes(run.id).filter(n=>n.status==="pending")});}catch(e){this.failNode(run,node,`REPLAN_FAILED: ${(e as Error).message}`,false,"FAILED");return;}const db=getDb(),now=Date.now(),generation=run.generation+1;db.transaction(()=>{db.prepare(`UPDATE plan_nodes SET status='abandoned',updated_at=? WHERE plan_run_id=? AND status='pending'`).run(now,run.id);db.prepare(`UPDATE plan_nodes SET status='failed',error=?,claimed_at=NULL,updated_at=? WHERE id=?`).run(error,now,node.id);const ids=new Map(specs.map(s=>[s.local_id,randomUUID()]));const q=db.prepare(`INSERT INTO plan_nodes(id,parent_id,title,status,created_at,plan_run_id,position,generation,capability,objective,context_json,constraints_json,priority,dependencies_json,updated_at,attempt)VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,1)`);specs.forEach((s,i)=>q.run(ids.get(s.local_id),run.rootNodeId,s.title,"pending",now,run.id,i,generation,s.capability,s.objective,JSON.stringify(s.context),JSON.stringify(s.constraints),s.priority,JSON.stringify(s.depends_on.map(d=>ids.get(d))),now));db.prepare(`UPDATE plan_runs SET status='RUNNING',generation=?,replan_count=replan_count+1,last_error=?,updated_at=? WHERE id=?`).run(generation,error,now,run.id);})();}
 cancel(runId:string){const run=this.planner.getRun(runId);if(!run)return null;let uncertain=false;for(const n of this.planner.nodes(runId)){if(n.status==="pending")this.planner.setStatus(n.id,"cancelled");if(n.operationTaskId&&(n.status==="in_progress"||n.status==="waiting")){const r=this.orchestrator.store.cancel(n.operationTaskId);if(r&&!r.cancelled)uncertain=true;else this.planner.setStatus(n.id,"cancelled");}}this.planner.updateRun(runId,uncertain?"BLOCKED":"CANCELLED",uncertain?"CANCELLATION_REQUESTED_OPERATION_IN_PROGRESS":undefined);if(!uncertain)this.planner.setStatus(run.rootNodeId,"cancelled");return this.planner.getRun(runId);}
}
